/**
 * @module CRM Seeds
 * @description Datos semilla del módulo CRM Escolar de ISkool.
 *   Prospectos de ejemplo distribuidos en múltiples campus y etapas del pipeline.
 *   Incluye candidatos, actividades y documentos de referencia.
 */
import type {
  CrmLead, CrmLeadCandidate, CrmActivity, CrmDocument, CrmEvent, CrmEventAttendee
} from '@/types/crm';

// ============================================================
// LEADS (Prospectos Familiares)
// ============================================================

export const CRM_LEADS_SEED: CrmLead[] = [
  // --- IBIME: Campus Montes ---
  {
    id: 'lead-001',
    school_id: 'sch-ibime',
    campus_id: 'montes',
    pipeline_type: 'new_enrollment',
    stage: 'reservation',
    tutor_first_name: 'Fernando',
    tutor_last_name_1: 'Reyes',
    tutor_last_name_2: 'Gutiérrez',
    tutor_last_name: 'Reyes Gutiérrez',
    tutor_phone: '55 4192 8841',
    tutor_email: 'fernando.reyes@email.com',
    tutor_relationship: 'Padre',
    source_channel: 'referral',
    source_detail: 'Recomendado por familia Garza (alumno activo en 4° Primaria)',
    lead_score: 85,
    assigned_to: 'staff-adm-ibime-1',
    assigned_to_name: 'Lic. Mariana Solís',
    priority: 'hot',
    referred_by_family_id: 'lead-003',
    referred_by_family_name: 'Familia Garza Morales',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Carta emitida con plaza reservada en 2° A Bilingüe. En espera de pago de inscripción vía SPEI.',
    created_at: '2026-09-20T10:30:00Z',
    updated_at: '2026-09-22T14:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 75,
    days_in_current_stage: 1,
    campus_name: 'Campus Montes (Sede Matriz & CCH)',
  },
  {
    id: 'lead-002',
    school_id: 'sch-ibime',
    campus_id: 'montes',
    pipeline_type: 'new_enrollment',
    stage: 'tour_scheduled',
    tutor_first_name: 'Carlos',
    tutor_last_name_1: 'Montes',
    tutor_last_name_2: 'Villanueva',
    tutor_last_name: 'Montes Villanueva',
    tutor_phone: '55 9012 3456',
    tutor_email: 'carlos.montes@techcorp.mx',
    tutor_relationship: 'Padre',
    source_channel: 'corporate_agreement',
    source_detail: 'Convenio TechCorp México — Descuento 10% corporativo',
    lead_score: 60,
    assigned_to: 'staff-adm-ibime-1',
    assigned_to_name: 'Lic. Mariana Solís',
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Tour guiado por laboratorios STEAM, canchas y aulas CCH completado con el Director.',
    created_at: '2026-09-21T09:00:00Z',
    updated_at: '2026-09-22T16:30:00Z',
    candidates_count: 1,
    documents_complete_percent: 0,
    days_in_current_stage: 1,
    campus_name: 'Campus Montes (Sede Matriz & CCH)',
  },
  // --- IBIME: Campus Lagos ---
  {
    id: 'lead-003',
    school_id: 'sch-ibime',
    campus_id: 'lagos',
    pipeline_type: 'new_enrollment',
    stage: 'enrolled',
    tutor_first_name: 'Roberto',
    tutor_last_name: 'Garza Morales',
    tutor_phone: '55 3190 2481',
    tutor_email: 'roberto.garza@hospital.com',
    tutor_relationship: 'Padre',
    source_channel: 'referral',
    source_detail: 'Recomendado por el Dr. Guzmán (abuelo de alumna en 6°)',
    lead_score: 100,
    assigned_to: 'staff-adm-ibime-2',
    assigned_to_name: 'Mtra. Lucía Hernández',
    priority: 'hot',
    referral_incentive_applied: true,
    outcome: 'enrolled',
    target_academic_year: '2027-2028',
    notes: 'Inscripción liquidada al 100%. CFDI 4.0 con complemento IEDU emitido.',
    created_at: '2026-09-15T08:00:00Z',
    updated_at: '2026-09-20T11:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 100,
    days_in_current_stage: 3,
    campus_name: 'Campus Lagos (Fundador 2004)',
  },
  {
    id: 'lead-004',
    school_id: 'sch-ibime',
    campus_id: 'lagos',
    pipeline_type: 'new_enrollment',
    stage: 'tour_scheduled',
    tutor_first_name: 'Patricia',
    tutor_last_name: 'Cordero Linares',
    tutor_phone: '55 2381 0092',
    tutor_email: 'patricia.cordero@estudio.mx',
    tutor_relationship: 'Madre',
    source_channel: 'referral',
    lead_score: 45,
    assigned_to: 'staff-adm-ibime-2',
    assigned_to_name: 'Mtra. Lucía Hernández',
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Visita con directores de Lagos completada. Agendando prueba diagnóstica bilingüe.',
    created_at: '2026-09-20T11:00:00Z',
    updated_at: '2026-09-22T09:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 12,
    days_in_current_stage: 1,
    campus_name: 'Campus Lagos (Fundador 2004)',
  },
  // --- IBIME: Campus San Cristóbal ---
  {
    id: 'lead-005',
    school_id: 'sch-ibime',
    campus_id: 'sancristobal',
    pipeline_type: 'new_enrollment',
    stage: 'evaluation',
    tutor_first_name: 'Claudia',
    tutor_last_name: 'Albarrán Rivas',
    tutor_phone: '55 8320 1194',
    tutor_email: 'claudia.albarran@email.com',
    tutor_relationship: 'Madre',
    source_channel: 'facebook',
    source_detail: 'Campaña "Inscripciones 2027" — Meta Ads',
    lead_score: 65,
    assigned_to: 'staff-adm-ibime-3',
    assigned_to_name: 'Lic. Andrea Vega',
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Diagnóstico psicopedagógico completado. Dictamen favorable para programa Cambridge KET.',
    created_at: '2026-09-18T14:00:00Z',
    updated_at: '2026-09-22T10:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 25,
    days_in_current_stage: 1,
    campus_name: 'Campus San Cristóbal (Ecatepec Centro)',
  },
  {
    id: 'lead-006',
    school_id: 'sch-ibime',
    campus_id: 'sancristobal',
    pipeline_type: 'new_enrollment',
    stage: 'reservation',
    tutor_first_name: 'Javier',
    tutor_last_name: 'Pineda Muñoz',
    tutor_phone: '55 8129 9033',
    tutor_email: 'javier.pineda@notaria.mx',
    tutor_relationship: 'Padre',
    source_channel: 'school_fair',
    source_detail: 'Feria de Colegios Ecatepec 2026',
    lead_score: 80,
    assigned_to: 'staff-adm-ibime-3',
    assigned_to_name: 'Lic. Andrea Vega',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Cupo asignado en 3° B Secundaria. Fecha límite de pago: 3 días hábiles.',
    created_at: '2026-09-19T09:30:00Z',
    updated_at: '2026-09-22T15:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 62,
    days_in_current_stage: 1,
    campus_name: 'Campus San Cristóbal (Ecatepec Centro)',
  },
  // --- IBIME: Campus Coacalco ---
  {
    id: 'lead-007',
    school_id: 'sch-ibime',
    campus_id: 'coacalco',
    pipeline_type: 'new_enrollment',
    stage: 'registered',
    tutor_first_name: 'Andrea',
    tutor_last_name: 'Ruiz Moreno',
    tutor_phone: '55 3901 1284',
    tutor_email: 'andrea.ruiz@salud.gob.mx',
    tutor_relationship: 'Madre',
    source_channel: 'website_form',
    lead_score: 20,
    assigned_to: 'staff-adm-ibime-4',
    assigned_to_name: 'Lic. Daniel Flores',
    priority: 'normal',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Formulario web completado desde portal. Asesor asignado para llamada de bienvenida.',
    created_at: '2026-09-22T08:00:00Z',
    updated_at: '2026-09-22T08:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 0,
    days_in_current_stage: 1,
    campus_name: 'Campus Coacalco (Metropolitano)',
  },
  {
    id: 'lead-008',
    school_id: 'sch-ibime',
    campus_id: 'coacalco',
    pipeline_type: 'new_enrollment',
    stage: 'evaluation',
    tutor_first_name: 'Daniel',
    tutor_last_name: 'Carrillo Treviño',
    tutor_phone: '55 4910 8273',
    tutor_email: 'daniel.carrillo@profesor.mx',
    tutor_relationship: 'Padre',
    source_channel: 'instagram',
    source_detail: 'Reel "Un Día en IBIME Coacalco" — 82K views',
    lead_score: 55,
    assigned_to: 'staff-adm-ibime-4',
    assigned_to_name: 'Lic. Daniel Flores',
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Entrevista con psicopedagoga aprobada con felicitaciones de coordinación.',
    created_at: '2026-09-17T10:00:00Z',
    updated_at: '2026-09-22T13:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 37,
    days_in_current_stage: 1,
    campus_name: 'Campus Coacalco (Metropolitano)',
  },
  {
    id: 'lead-009',
    school_id: 'sch-ibime',
    campus_id: 'coacalco',
    pipeline_type: 'new_enrollment',
    stage: 'registered',
    tutor_first_name: 'Héctor',
    tutor_last_name: 'Ortiz Delgado',
    tutor_phone: '55 7104 4455',
    tutor_email: 'hector.ortiz@aero.com',
    tutor_relationship: 'Padre',
    source_channel: 'referral',
    source_detail: 'Recomendado por familia activa en Primaria Coacalco',
    lead_score: 30,
    assigned_to: 'staff-adm-ibime-4',
    assigned_to_name: 'Lic. Daniel Flores',
    priority: 'normal',
    referred_by_family_name: 'Familia Romero (Primaria Coacalco)',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Interés por recomendación familiar. Solicitó informes de costos y programa bilingüe.',
    created_at: '2026-09-23T09:00:00Z',
    updated_at: '2026-09-23T09:00:00Z',
    candidates_count: 2,
    documents_complete_percent: 0,
    days_in_current_stage: 0,
    campus_name: 'Campus Coacalco (Metropolitano)',
  },
  // --- Lead declinado para métricas ---
  {
    id: 'lead-010',
    school_id: 'sch-ibime',
    campus_id: 'montes',
    pipeline_type: 'new_enrollment',
    stage: 'declined',
    tutor_first_name: 'Laura',
    tutor_last_name: 'Mendoza Torres',
    tutor_phone: '55 6100 3322',
    tutor_email: 'laura.mendoza@corp.mx',
    tutor_relationship: 'Madre',
    source_channel: 'facebook',
    source_detail: 'Campaña "Back to School" — Facebook Lead Ads',
    lead_score: 10,
    assigned_to: 'staff-adm-ibime-1',
    assigned_to_name: 'Lic. Mariana Solís',
    priority: 'cold',
    referral_incentive_applied: false,
    outcome: 'declined',
    lost_reason: 'price',
    lost_to_school: 'Colegio Williams',
    target_academic_year: '2027-2028',
    notes: 'Familia declinó por precio de colegiatura. Eligió Colegio Williams (20% más económico).',
    created_at: '2026-09-10T08:00:00Z',
    updated_at: '2026-09-18T16:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 0,
    days_in_current_stage: 5,
    campus_name: 'Campus Montes (Sede Matriz & CCH)',
  },
  // --- JJR: Ejemplo en otro colegio ---
  {
    id: 'lead-011',
    school_id: 'sch-jjrosseau',
    campus_id: 'primaria-jardines',
    pipeline_type: 'new_enrollment',
    stage: 'contacted',
    tutor_first_name: 'Gabriela',
    tutor_last_name: 'Sánchez Luna',
    tutor_phone: '55 1234 5678',
    tutor_email: 'gabriela.sanchez@mail.com',
    tutor_relationship: 'Madre',
    source_channel: 'walk_in',
    lead_score: 35,
    assigned_to: 'staff-coord-jjr-1',
    assigned_to_name: 'Mtra. Rosa Jiménez',
    priority: 'normal',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Llegó directamente al plantel preguntando por cupo en 3° Primaria para su hijo.',
    created_at: '2026-09-22T11:00:00Z',
    updated_at: '2026-09-23T10:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 0,
    days_in_current_stage: 0,
    campus_name: 'Primaria Jardines',
  },
  // --- Reinscripción ejemplo ---
  {
    id: 'lead-012',
    school_id: 'sch-ibime',
    campus_id: 'montes',
    pipeline_type: 'reenrollment',
    stage: 'census',
    tutor_first_name: 'Ricardo',
    tutor_last_name: 'Domínguez Pérez',
    tutor_phone: '55 8899 1122',
    tutor_email: 'ricardo.dominguez@empresa.mx',
    tutor_relationship: 'Padre',
    source_channel: 'other',
    lead_score: 70,
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Familia actual con 2 hijos en Primaria Montes. Encuesta de intención enviada.',
    created_at: '2026-09-15T09:00:00Z',
    updated_at: '2026-09-20T09:00:00Z',
    candidates_count: 2,
    documents_complete_percent: 100,
    days_in_current_stage: 3,
    campus_name: 'Campus Montes (Sede Matriz & CCH)',
  },

  // ============================================================
  // 10 CASOS DE DEMOSTRACIÓN B2B (ETAPAS DISTRIBUIDAS)
  // ============================================================

  // DEMO 1: Etapa "registered" — Lead caliente recién ingresado por WhatsApp nocturno
  {
    id: 'lead-013',
    school_id: 'sch-ibime',
    campus_id: 'montes',
    pipeline_type: 'new_enrollment',
    stage: 'registered',
    tutor_first_name: 'Mauricio',
    tutor_last_name_1: 'Treviño',
    tutor_last_name_2: 'Elizondo',
    tutor_last_name: 'Treviño Elizondo',
    tutor_phone: '55 7712 9044',
    tutor_email: 'mauricio.trevino@nortecorp.mx',
    tutor_relationship: 'Padre',
    source_channel: 'whatsapp_direct',
    source_detail: 'WhatsApp directo: mensaje a las 11:30 PM solicitando cuotas urgentes',
    lead_score: 45,
    assigned_to: 'staff-adm-ibime-1',
    assigned_to_name: 'Lic. Mariana Solís',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Familia reubicándose desde Monterrey a CDMX por cambio de corporativo. Urgencia alta de plaza en 2° Primaria Bilingüe.',
    created_at: '2026-09-24T05:30:00Z',
    updated_at: '2026-09-24T05:30:00Z',
    candidates_count: 1,
    documents_complete_percent: 0,
    days_in_current_stage: 0,
    campus_name: 'Campus Montes (Sede Matriz & CCH)',
  },

  // DEMO 2: Etapa "contacted" — Pidiendo informes de preescolar vía campaña de Facebook Ads
  {
    id: 'lead-014',
    school_id: 'sch-ibime',
    campus_id: 'lagos',
    pipeline_type: 'new_enrollment',
    stage: 'contacted',
    tutor_first_name: 'Claudia Marcela',
    tutor_last_name_1: 'Ibarra',
    tutor_last_name_2: 'Navarrete',
    tutor_last_name: 'Ibarra Navarrete',
    tutor_phone: '55 3301 8892',
    tutor_email: 'claudia.ibarra@arquitectura.com',
    tutor_relationship: 'Madre',
    source_channel: 'facebook',
    source_detail: 'Campaña Meta Ads: Preescolar Activo y Pensamiento Lógico',
    lead_score: 35,
    assigned_to: 'staff-adm-ibime-2',
    assigned_to_name: 'Mtra. Lucía Hernández',
    priority: 'normal',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Madre interesada en formación temprana con enfoque lúdico y bilingüismo. Se compartió folleto institucional y cuotas por WhatsApp.',
    created_at: '2026-09-23T16:00:00Z',
    updated_at: '2026-09-24T03:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 0,
    days_in_current_stage: 0,
    campus_name: 'Campus Lagos',
  },

  // DEMO 3: Etapa "tour_scheduled" — Recomendado familiar con cita este viernes
  {
    id: 'lead-015',
    school_id: 'sch-ibime',
    campus_id: 'montes',
    pipeline_type: 'new_enrollment',
    stage: 'tour_scheduled',
    tutor_first_name: 'Rodrigo',
    tutor_last_name_1: 'Alcocer',
    tutor_last_name_2: 'Peón',
    tutor_last_name: 'Alcocer Peón',
    tutor_phone: '55 8812 3409',
    tutor_email: 'rodrigo.alcocer@invercapital.com',
    tutor_relationship: 'Padre',
    source_channel: 'referral',
    source_detail: 'Recomendado por la familia Garza Morales (alumnos en 4° Primaria)',
    lead_score: 65,
    assigned_to: 'staff-adm-ibime-1',
    assigned_to_name: 'Lic. Mariana Solís',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Interés prioritario en robótica y certificación Cambridge. Cita presencial agendada este viernes 10:30 AM para recorrido por laboratorios STEAM.',
    created_at: '2026-09-22T12:00:00Z',
    updated_at: '2026-09-23T18:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 25,
    days_in_current_stage: 1,
    campus_name: 'Campus Montes (Sede Matriz & CCH)',
  },

  // DEMO 4: Etapa "tour_scheduled" — Captada en Open House para Preparatoria
  {
    id: 'lead-016',
    school_id: 'sch-ibime',
    campus_id: 'montes',
    pipeline_type: 'new_enrollment',
    stage: 'tour_scheduled',
    tutor_first_name: 'Patricia',
    tutor_last_name_1: 'Zepeda',
    tutor_last_name_2: 'Cuéllar',
    tutor_last_name: 'Zepeda Cuéllar',
    tutor_phone: '55 6234 1178',
    tutor_email: 'patricia.zepeda@medicasur.com.mx',
    tutor_relationship: 'Madre',
    source_channel: 'open_house',
    source_detail: 'Asistió al Open House de Preparatoria y Bachillerato CCH',
    lead_score: 55,
    assigned_to: 'staff-adm-ibime-1',
    assigned_to_name: 'Lic. Mariana Solís',
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Médico especialista en Hospital Médica Sur. Su hijo busca perfil en Ciencias de la Salud con pase reglamentado/convenio universitario.',
    created_at: '2026-09-21T10:00:00Z',
    updated_at: '2026-09-23T11:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 25,
    days_in_current_stage: 2,
    campus_name: 'Campus Montes (Sede Matriz & CCH)',
  },

  // DEMO 5: Etapa "evaluation" — Examen diagnóstico psicopedagógico completado con 95/100
  {
    id: 'lead-017',
    school_id: 'sch-ibime',
    campus_id: 'montes',
    pipeline_type: 'new_enrollment',
    stage: 'evaluation',
    tutor_first_name: 'Gerardo',
    tutor_last_name_1: 'Baeza',
    tutor_last_name_2: 'Salmón',
    tutor_last_name: 'Baeza Salmón',
    tutor_phone: '55 9123 4567',
    tutor_email: 'gerardo.baeza@despacho.com.mx',
    tutor_relationship: 'Padre',
    source_channel: 'google',
    source_detail: 'Búsqueda orgánica en Google: mejores colegios bilingües sur cdmx',
    lead_score: 75,
    assigned_to: 'staff-adm-ibime-1',
    assigned_to_name: 'Lic. Mariana Solís',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Evaluación diagnóstica psicopedagógica aplicada ayer. La psicóloga del plantel reporta excelente nivel cognitivo y madurez sobresaliente.',
    created_at: '2026-09-19T09:30:00Z',
    updated_at: '2026-09-23T15:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 60,
    days_in_current_stage: 1,
    campus_name: 'Campus Montes (Sede Matriz & CCH)',
  },

  // DEMO 6: Etapa "evaluation" — 2 Hermanos con convenio corporativo BBVA
  {
    id: 'lead-018',
    school_id: 'sch-ibime',
    campus_id: 'lagos',
    pipeline_type: 'new_enrollment',
    stage: 'evaluation',
    tutor_first_name: 'Liliana',
    tutor_last_name_1: 'Carrillo',
    tutor_last_name_2: 'Fontes',
    tutor_last_name: 'Carrillo Fontes',
    tutor_phone: '55 4567 8901',
    tutor_email: 'liliana.carrillo@estudioarq.com',
    tutor_relationship: 'Madre',
    source_channel: 'corporate_agreement',
    source_detail: 'Convenio Corporativo BBVA Bancomer — 15% descuento en colegiaturas',
    lead_score: 70,
    assigned_to: 'staff-adm-ibime-2',
    assigned_to_name: 'Mtra. Lucía Hernández',
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Familia con 2 hermanitos para ingresar en Primaria. Ambos presentaron evaluación de colocación de inglés con resultado aprobatorio.',
    created_at: '2026-09-20T11:00:00Z',
    updated_at: '2026-09-23T17:00:00Z',
    candidates_count: 2,
    documents_complete_percent: 50,
    days_in_current_stage: 2,
    campus_name: 'Campus Lagos',
  },

  // DEMO 7: Etapa "proposal_sent" — Corrida financiera enviada con beca de excelencia
  {
    id: 'lead-019',
    school_id: 'sch-ibime',
    campus_id: 'montes',
    pipeline_type: 'new_enrollment',
    stage: 'proposal_sent',
    tutor_first_name: 'Fernando',
    tutor_last_name_1: 'Morales',
    tutor_last_name_2: 'Vivanco',
    tutor_last_name: 'Morales Vivanco',
    tutor_phone: '55 5678 9012',
    tutor_email: 'fernando.morales@cardiocenter.mx',
    tutor_relationship: 'Padre',
    source_channel: 'walk_in',
    source_detail: 'Visita presencial espontánea en horario matutino',
    lead_score: 85,
    assigned_to: 'staff-adm-ibime-1',
    assigned_to_name: 'Lic. Mariana Solís',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Se presentó y envió corrida financiera formal para 1° Secundaria con 20% de beca de excelencia académica por promedio 9.8 en boleta SEP.',
    created_at: '2026-09-18T10:00:00Z',
    updated_at: '2026-09-23T19:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 75,
    days_in_current_stage: 1,
    campus_name: 'Campus Montes (Sede Matriz & CCH)',
  },

  // DEMO 8: Etapa "reservation" — Apartado de cupo pagado en caja escolar ($3,500 MXN)
  {
    id: 'lead-020',
    school_id: 'sch-ibime',
    campus_id: 'pedregal',
    pipeline_type: 'new_enrollment',
    stage: 'reservation',
    tutor_first_name: 'Andrea',
    tutor_last_name_1: 'Villalobos',
    tutor_last_name_2: 'Cárdenas',
    tutor_last_name: 'Villalobos Cárdenas',
    tutor_phone: '55 6789 0123',
    tutor_email: 'andrea.villalobos@fintech.io',
    tutor_relationship: 'Madre',
    source_channel: 'referral',
    source_detail: 'Recomendada por la familia Treviño (amigos de la infancia)',
    lead_score: 90,
    assigned_to: 'staff-adm-ibime-3',
    assigned_to_name: 'Lic. Sofía Alatorre',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2027-2028',
    notes: 'Lugar apartado con anticipo de $3,500 MXN en caja escolar para Maternal A. Ficha bancaria validada en sistema. Falta comprobante de domicilio.',
    created_at: '2026-09-16T12:00:00Z',
    updated_at: '2026-09-23T20:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 85,
    days_in_current_stage: 1,
    campus_name: 'Campus Pedregal (Preescolar & Maternal)',
  },

  // DEMO 9: Etapa "enrolled" — Alumna 100% formalizada, matrícula asignada y expediente completo
  {
    id: 'lead-021',
    school_id: 'sch-ibime',
    campus_id: 'montes',
    pipeline_type: 'new_enrollment',
    stage: 'enrolled',
    tutor_first_name: 'Héctor',
    tutor_last_name_1: 'Salgado',
    tutor_last_name_2: 'Mendiola',
    tutor_last_name: 'Salgado Mendiola',
    tutor_phone: '55 7890 1234',
    tutor_email: 'hector.salgado@auditoria.mx',
    tutor_relationship: 'Padre',
    source_channel: 'school_fair',
    source_detail: 'Feria Escolar Interlomas & Santa Fe 2026',
    lead_score: 100,
    assigned_to: 'staff-adm-ibime-1',
    assigned_to_name: 'Lic. Mariana Solís',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: 'enrolled',
    target_academic_year: '2027-2028',
    notes: 'Inscripción anual liquidada vía transferencia bancaria SPEI. Matrícula oficial generada: MAT-2027-0142. Expediente 360 completo.',
    created_at: '2026-09-12T08:30:00Z',
    updated_at: '2026-09-22T13:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 100,
    days_in_current_stage: 2,
    campus_name: 'Campus Montes (Sede Matriz & CCH)',
  },

  // DEMO 10: Etapa "declined" — Declinó por reubicación familiar foránea a Querétaro
  {
    id: 'lead-022',
    school_id: 'sch-ibime',
    campus_id: 'montes',
    pipeline_type: 'new_enrollment',
    stage: 'declined',
    tutor_first_name: 'Daniela',
    tutor_last_name_1: 'Obregón',
    tutor_last_name_2: 'Téllez',
    tutor_last_name: 'Obregón Téllez',
    tutor_phone: '55 8901 2345',
    tutor_email: 'daniela.obregon@comunicacion.com',
    tutor_relationship: 'Madre',
    source_channel: 'facebook',
    source_detail: 'Campaña Meta Ads Secundaria Bilingüe',
    lead_score: 15,
    assigned_to: 'staff-adm-ibime-1',
    assigned_to_name: 'Lic. Mariana Solís',
    priority: 'cold',
    referral_incentive_applied: false,
    outcome: 'declined',
    lost_reason: 'city_relocation',
    lost_to_school: 'Colegio Peterson Querétaro',
    target_academic_year: '2027-2028',
    notes: 'Familia declinó por cambio imprevisto de residencia laboral a la ciudad de Querétaro. Se mantendrá en base de datos para futuras referencias.',
    created_at: '2026-09-14T09:00:00Z',
    updated_at: '2026-09-23T14:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 0,
    days_in_current_stage: 3,
    campus_name: 'Campus Montes (Sede Matriz & CCH)',
  },

  // ============================================================
  // PIPELINE B2B CORPORATIVO: BMW GROUP MÉXICO (emp-bmw)
  // Sedes: San Luis Potosí (cmp-bmw-slp) y Santa Fe CDMX (cmp-bmw-cdmx)
  // ============================================================
  {
    id: 'lead-bmw-001',
    school_id: 'emp-bmw',
    campus_id: 'cmp-bmw-slp',
    pipeline_type: 'corporate_recruitment',
    stage: 'registered',
    tutor_first_name: 'Daniel',
    tutor_last_name_1: 'Zavala',
    tutor_last_name_2: 'Ríos',
    tutor_last_name: 'Zavala Ríos',
    tutor_phone: '444 812 9044',
    tutor_email: 'daniel.zavala@ingenieria.mx',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'linkedin',
    source_detail: 'LinkedIn Talent Solutions — Campaña Robótica KUKA & Celdas San Luis Potosí',
    lead_score: 88,
    assigned_to: 'recruiter-bmw-1',
    assigned_to_name: 'Lic. Rodrigo Sánchez Monroy',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Ingeniero Mecatrónico con 6 años de experiencia en automatización de celdas robotizadas KUKA. Disponibilidad inmediata para turno matutino en planta SLP.',
    created_at: '2026-09-22T08:30:00Z',
    updated_at: '2026-09-23T10:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 40,
    days_in_current_stage: 1,
    campus_name: 'Planta San Luis Potosí (Manufactura y Ensamble)',
    proposed_salary: '$48,000 MXN / mes',
    department: 'Ensamble y Robótica Industrial',
    recruiter_name: 'Lic. Rodrigo Sánchez Monroy',
    recruiter_title: 'VP People & HR Industrial',
  },
  {
    id: 'lead-bmw-002',
    school_id: 'emp-bmw',
    campus_id: 'cmp-bmw-slp',
    pipeline_type: 'corporate_recruitment',
    stage: 'contacted',
    tutor_first_name: 'Paulina',
    tutor_last_name_1: 'Morales',
    tutor_last_name_2: 'Dávila',
    tutor_last_name: 'Morales Dávila',
    tutor_phone: '444 765 4321',
    tutor_email: 'paulina.morales@calidad.com.mx',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'internal_referral',
    source_detail: 'Referida por Ing. Guillermo Schmidt (Master Trainer BMW)',
    lead_score: 82,
    assigned_to: 'recruiter-bmw-1',
    assigned_to_name: 'Lic. Rodrigo Sánchez Monroy',
    priority: 'warm',
    referral_incentive_applied: true,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Auditora líder en normativas ISO 14001 y manejo ambiental de residuos en ensamblaje de módulos de tracción eléctrica.',
    created_at: '2026-09-21T11:00:00Z',
    updated_at: '2026-09-23T14:30:00Z',
    candidates_count: 1,
    documents_complete_percent: 60,
    days_in_current_stage: 2,
    campus_name: 'Planta San Luis Potosí (Manufactura y Ensamble)',
    proposed_salary: '$52,000 MXN / mes',
    department: 'Seguridad Industrial & Calidad ISO',
    recruiter_name: 'Lic. Rodrigo Sánchez Monroy',
    recruiter_title: 'VP People & HR Industrial',
  },
  {
    id: 'lead-bmw-003',
    school_id: 'emp-bmw',
    campus_id: 'cmp-bmw-slp',
    pipeline_type: 'corporate_recruitment',
    stage: 'tour_scheduled',
    tutor_first_name: 'Andrea',
    tutor_last_name_1: 'Pantoja',
    tutor_last_name_2: 'Cruz',
    tutor_last_name: 'Pantoja Cruz',
    tutor_phone: '444 980 1122',
    tutor_email: 'andrea.pantoja@evmotors.de',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'headhunting',
    source_detail: 'Headhunting Ejecutivo — Especialistas en Tren Motriz y Alto Voltaje',
    lead_score: 95,
    assigned_to: 'recruiter-bmw-1',
    assigned_to_name: 'Lic. Rodrigo Sánchez Monroy',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Entrevista técnica presencial programada en el Centro de Baterías de Planta SLP. Cuenta con certificación de seguridad en alto voltaje nivel 3.',
    created_at: '2026-09-20T09:00:00Z',
    updated_at: '2026-09-23T16:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 75,
    days_in_current_stage: 1,
    campus_name: 'Planta San Luis Potosí (Manufactura y Ensamble)',
    proposed_salary: '$54,000 MXN / mes',
    department: 'Centro de Ensamble Baterías Alto Voltaje',
    recruiter_name: 'Dra. Erika Von Humboldt',
    recruiter_title: 'Directora Técnica de Alto Voltaje',
  },
  {
    id: 'lead-bmw-004',
    school_id: 'emp-bmw',
    campus_id: 'cmp-bmw-slp',
    pipeline_type: 'corporate_recruitment',
    stage: 'evaluation',
    tutor_first_name: 'Mauricio',
    tutor_last_name_1: 'Garza',
    tutor_last_name_2: 'Treviño',
    tutor_last_name: 'Garza Treviño',
    tutor_phone: '444 321 8899',
    tutor_email: 'mauricio.garza@autotech.mx',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'job_board',
    source_detail: 'Bolsa de Empleo Técnica Automotriz México',
    lead_score: 92,
    assigned_to: 'recruiter-bmw-1',
    assigned_to_name: 'Lic. Rodrigo Sánchez Monroy',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Prueba psicométrica y prueba técnica en simulador KUKA concluidas con 93/100. Pendiente dictamen del comité de manufactura.',
    created_at: '2026-09-18T10:00:00Z',
    updated_at: '2026-09-23T11:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 85,
    days_in_current_stage: 2,
    campus_name: 'Planta San Luis Potosí (Manufactura y Ensamble)',
    proposed_salary: '$58,000 MXN / mes',
    department: 'Ensamble y Robótica Industrial',
    recruiter_name: 'Ing. Guillermo Schmidt Keller',
    recruiter_title: 'Master Trainer & Jefe de Evaluación',
  },
  {
    id: 'lead-bmw-005',
    school_id: 'emp-bmw',
    campus_id: 'cmp-bmw-cdmx',
    pipeline_type: 'corporate_recruitment',
    stage: 'proposal_sent',
    tutor_first_name: 'Claudia',
    tutor_last_name_1: 'Morales',
    tutor_last_name_2: 'Ortiz',
    tutor_last_name: 'Morales Ortiz',
    tutor_phone: '55 4567 1122',
    tutor_email: 'claudia.morales@logistics.org',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'corporate_agreement',
    source_detail: 'Convenio con Clúster Logístico Automotriz Centro-Norte',
    lead_score: 90,
    assigned_to: 'recruiter-bmw-2',
    assigned_to_name: 'Lic. Andrea Fuentes (HR Santa Fe)',
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Carta oferta económica emitida por $45,000 MXN brutos con prestaciones superiores (SGMM, fondo de ahorro y bono de productividad trimestral).',
    created_at: '2026-09-17T14:00:00Z',
    updated_at: '2026-09-23T17:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 90,
    days_in_current_stage: 1,
    campus_name: 'Corporativo Nexus Santa Fe',
    proposed_salary: '$45,000 MXN / mes',
    department: 'Logística & Cadena de Suministro JIT',
    recruiter_name: 'Lic. Andrea Fuentes',
    recruiter_title: 'Coordinadora de Atracción Santa Fe',
  },
  {
    id: 'lead-bmw-006',
    school_id: 'emp-bmw',
    campus_id: 'cmp-bmw-slp',
    pipeline_type: 'corporate_recruitment',
    stage: 'enrolled',
    tutor_first_name: 'Fernando',
    tutor_last_name_1: 'Schmidt',
    tutor_last_name_2: 'Keller',
    tutor_last_name: 'Schmidt Keller',
    tutor_phone: '444 199 4433',
    tutor_email: 'fernando.schmidt@bmw-corp.mx',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'linkedin',
    source_detail: 'Búsqueda ejecutiva directa por dirección general',
    lead_score: 99,
    assigned_to: 'recruiter-bmw-1',
    assigned_to_name: 'Lic. Rodrigo Sánchez Monroy',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: 'enrolled',
    target_academic_year: '2026-2027',
    notes: 'Contrato firmado al 100%. Alta patronal IMSS procesada. Entrega de credencial corporativa, EPP y kit de inducción completada.',
    created_at: '2026-09-10T08:00:00Z',
    updated_at: '2026-09-22T15:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 100,
    days_in_current_stage: 2,
    campus_name: 'Planta San Luis Potosí (Manufactura y Ensamble)',
    proposed_salary: '$65,000 MXN / mes',
    department: 'Investigación & Desarrollo de Baterías',
    recruiter_name: 'Ing. Dirk Dreher',
    recruiter_title: 'CEO & Director General BMW Group México',
  },
  {
    id: 'lead-bmw-007',
    school_id: 'emp-bmw',
    campus_id: 'cmp-bmw-cdmx',
    pipeline_type: 'corporate_recruitment',
    stage: 'tour_scheduled',
    tutor_first_name: 'Gabriel',
    tutor_last_name_1: 'Ramos',
    tutor_last_name_2: 'Lozano',
    tutor_last_name: 'Ramos Lozano',
    tutor_phone: '55 6789 9900',
    tutor_email: 'gabriel.ramos@servicios.com',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'job_board',
    source_detail: 'Bolsa de Talentos Automotriz CDMX',
    lead_score: 78,
    assigned_to: 'recruiter-bmw-2',
    assigned_to_name: 'Lic. Andrea Fuentes (HR Santa Fe)',
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Entrevista inicial agendada con la gerencia de postventa Santa Fe. Evaluación de CRM y atención de garantías premium.',
    created_at: '2026-09-22T10:00:00Z',
    updated_at: '2026-09-23T12:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 50,
    days_in_current_stage: 1,
    campus_name: 'Corporativo Nexus Santa Fe',
    proposed_salary: '$42,000 MXN / mes',
    department: 'Comercial & Postventa Santa Fe',
    recruiter_name: 'Lic. Andrea Fuentes',
    recruiter_title: 'Coordinadora de Atracción Santa Fe',
  },
  {
    id: 'lead-bmw-008',
    school_id: 'emp-bmw',
    campus_id: 'cmp-bmw-slp',
    pipeline_type: 'corporate_recruitment',
    stage: 'reservation',
    tutor_first_name: 'Jorge Alberto',
    tutor_last_name_1: 'Rivas',
    tutor_last_name_2: 'Villarreal',
    tutor_last_name: 'Rivas Villarreal',
    tutor_phone: '444 555 7788',
    tutor_email: 'jorge.rivas@mecanica.edu.mx',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'internal_referral',
    source_detail: 'Recomendación de cuadrilla de ensamble KUKA turno vespertino',
    lead_score: 90,
    assigned_to: 'recruiter-bmw-1',
    assigned_to_name: 'Lic. Rodrigo Sánchez Monroy',
    priority: 'hot',
    referral_incentive_applied: true,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Oferta económica aceptada formalmente. Expediente médico laboral aprobado. En espera de fecha oficial de inducción en planta.',
    created_at: '2026-09-15T09:30:00Z',
    updated_at: '2026-09-23T18:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 95,
    days_in_current_stage: 1,
    campus_name: 'Planta San Luis Potosí (Manufactura y Ensamble)',
    proposed_salary: '$34,000 MXN / mes',
    department: 'Mantenimiento Preventivo Celdas KUKA',
    recruiter_name: 'Lic. Rodrigo Sánchez Monroy',
    recruiter_title: 'VP People & HR Industrial',
  },

  // ============================================================
  // PIPELINE B2B CORPORATIVO: GRUPO COMERCIAL VANGUARDIA RETAIL (emp-ventas)
  // Sedes: CEDIS Monterrey (cmp-ventas-mty), Insurgentes CDMX (cmp-ventas-cdmx), GDL (cmp-ventas-gdl)
  // ============================================================
  {
    id: 'lead-ventas-001',
    school_id: 'emp-ventas',
    campus_id: 'cmp-ventas-cdmx',
    pipeline_type: 'corporate_recruitment',
    stage: 'registered',
    tutor_first_name: 'Valeria',
    tutor_last_name_1: 'Santos',
    tutor_last_name_2: 'Orozco',
    tutor_last_name: 'Santos Orozco',
    tutor_phone: '55 1234 5678',
    tutor_email: 'valeria.santos@retail.mx',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'linkedin',
    source_detail: 'Convocatoria Directiva Retail Omnicanal 2026',
    lead_score: 84,
    assigned_to: 'recruiter-ventas-1',
    assigned_to_name: 'Lic. Bernardo Garza (VP Comercial)',
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Experiencia en negociación de categorías de consumo masivo con proveedores nacionales e internacionales.',
    created_at: '2026-09-22T09:00:00Z',
    updated_at: '2026-09-23T11:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 50,
    days_in_current_stage: 1,
    campus_name: 'Corporativo Insurgentes CDMX',
    proposed_salary: '$42,000 MXN / mes',
    department: 'Compras Corporativas & Retail Omnicanal',
    recruiter_name: 'Lic. Bernardo Garza',
    recruiter_title: 'VP Comercial & Desarrollo',
  },
  {
    id: 'lead-ventas-002',
    school_id: 'emp-ventas',
    campus_id: 'cmp-ventas-mty',
    pipeline_type: 'corporate_recruitment',
    stage: 'tour_scheduled',
    tutor_first_name: 'Rodrigo',
    tutor_last_name_1: 'Villarreal',
    tutor_last_name_2: 'Sada',
    tutor_last_name: 'Villarreal Sada',
    tutor_phone: '81 8345 6789',
    tutor_email: 'rodrigo.villarreal@logistica.com',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'job_board',
    source_detail: 'Bolsa de Trabajo Transporte & Cadena de Suministro MTY',
    lead_score: 89,
    assigned_to: 'recruiter-ventas-2',
    assigned_to_name: 'Lic. Mariana Garza Sada (CEO)',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Visita técnica programada en CEDIS Apodaca para evaluar patios de maniobras y rutas metropolitanas.',
    created_at: '2026-09-20T10:00:00Z',
    updated_at: '2026-09-23T13:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 70,
    days_in_current_stage: 1,
    campus_name: 'CEDIS Norte Monterrey (Cadena Logística)',
    proposed_salary: '$36,000 MXN / mes',
    department: 'Operaciones Logísticas & Flotas CEDIS',
    recruiter_name: 'Mtro. Javier Alarcón Castillo',
    recruiter_title: 'Director de Cadena de Suministro',
  },
  {
    id: 'lead-ventas-003',
    school_id: 'emp-ventas',
    campus_id: 'cmp-ventas-gdl',
    pipeline_type: 'corporate_recruitment',
    stage: 'evaluation',
    tutor_first_name: 'Brenda',
    tutor_last_name_1: 'Covarrubias',
    tutor_last_name_2: 'Lara',
    tutor_last_name: 'Covarrubias Lara',
    tutor_phone: '33 3456 7890',
    tutor_email: 'brenda.covarrubias@wms.com',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'headhunting',
    source_detail: 'Búsqueda de Talentos Logísticos Jalisco',
    lead_score: 87,
    assigned_to: 'recruiter-ventas-1',
    assigned_to_name: 'Lic. Bernardo Garza',
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Evaluación técnica de software WMS y auditoría de inventarios cíclicos con calificación de 92%.',
    created_at: '2026-09-19T08:00:00Z',
    updated_at: '2026-09-23T15:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 80,
    days_in_current_stage: 2,
    campus_name: 'Hub Logístico Guadalajara',
    proposed_salary: '$38,000 MXN / mes',
    department: 'Almacén & Distribución Occidente',
    recruiter_name: 'Mtro. Javier Alarcón Castillo',
    recruiter_title: 'Director de Cadena de Suministro',
  },
  {
    id: 'lead-ventas-004',
    school_id: 'emp-ventas',
    campus_id: 'cmp-ventas-cdmx',
    pipeline_type: 'corporate_recruitment',
    stage: 'proposal_sent',
    tutor_first_name: 'Carlos',
    tutor_last_name_1: 'Alcocer',
    tutor_last_name_2: 'Ramos',
    tutor_last_name: 'Alcocer Ramos',
    tutor_phone: '55 9876 1234',
    tutor_email: 'carlos.alcocer@kam.com.mx',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'internal_referral',
    source_detail: 'Referido del equipo comercial de autoservicios',
    lead_score: 93,
    assigned_to: 'recruiter-ventas-1',
    assigned_to_name: 'Lic. Bernardo Garza',
    priority: 'hot',
    referral_incentive_applied: true,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Propuesta de compensación fija más esquema de comisiones y bonos de cumplimiento de cuota trimestral.',
    created_at: '2026-09-17T11:00:00Z',
    updated_at: '2026-09-23T16:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 90,
    days_in_current_stage: 1,
    campus_name: 'Corporativo Insurgentes CDMX',
    proposed_salary: '$46,000 MXN / mes',
    department: 'Fuerza Comercial KAM Cuentas Clave',
    recruiter_name: 'Lic. Bernardo Garza',
    recruiter_title: 'VP Comercial & Desarrollo',
  },
  {
    id: 'lead-ventas-005',
    school_id: 'emp-ventas',
    campus_id: 'cmp-ventas-mty',
    pipeline_type: 'corporate_recruitment',
    stage: 'enrolled',
    tutor_first_name: 'Mónica',
    tutor_last_name_1: 'Terán',
    tutor_last_name_2: 'Sepúlveda',
    tutor_last_name: 'Terán Sepúlveda',
    tutor_phone: '81 9988 7766',
    tutor_email: 'monica.teran@vanguardia-retail.mx',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'corporate_agreement',
    source_detail: 'Selección Ejecutiva Directa por Consejo Directivo',
    lead_score: 98,
    assigned_to: 'recruiter-ventas-2',
    assigned_to_name: 'Lic. Mariana Garza Sada (CEO)',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: 'enrolled',
    target_academic_year: '2026-2027',
    notes: 'Contratada formalmente. Expediente laboral y registro en nómina de Monterrey concluido.',
    created_at: '2026-09-11T09:00:00Z',
    updated_at: '2026-09-22T14:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 100,
    days_in_current_stage: 2,
    campus_name: 'CEDIS Norte Monterrey (Cadena Logística)',
    proposed_salary: '$52,000 MXN / mes',
    department: 'Dirección de Experiencia del Cliente',
    recruiter_name: 'Lic. Mariana Garza Sada',
    recruiter_title: 'CEO & Directora General Vanguardia Retail',
  },
  {
    id: 'lead-ventas-006',
    school_id: 'emp-ventas',
    campus_id: 'cmp-ventas-gdl',
    pipeline_type: 'corporate_recruitment',
    stage: 'reservation',
    tutor_first_name: 'Andrés',
    tutor_last_name_1: 'Peñaloza',
    tutor_last_name_2: 'Guzmán',
    tutor_last_name: 'Peñaloza Guzmán',
    tutor_phone: '33 2211 4455',
    tutor_email: 'andres.penaloza@stock.mx',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'job_board',
    source_detail: 'Portal de Empleo Logístico Occidente',
    lead_score: 86,
    assigned_to: 'recruiter-ventas-1',
    assigned_to_name: 'Lic. Bernardo Garza',
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Aceptó propuesta económica para supervisar turnos de fin de semana y balanceo de existencias en el Hub GDL.',
    created_at: '2026-09-16T12:00:00Z',
    updated_at: '2026-09-23T18:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 90,
    days_in_current_stage: 1,
    campus_name: 'Hub Logístico Guadalajara',
    proposed_salary: '$32,000 MXN / mes',
    department: 'Inventarios Cíclicos & Control de Pérdidas',
    recruiter_name: 'Mtro. Javier Alarcón Castillo',
    recruiter_title: 'Director de Cadena de Suministro',
  },

  // ============================================================
  // PIPELINE B2B CORPORATIVO: INNOVASOFT TECH DYNAMICS (emp-tech)
  // Sedes: Tech Hub Guadalajara (cmp-tech-gdl), Polanco CDMX (cmp-tech-cdmx)
  // ============================================================
  {
    id: 'lead-tech-001',
    school_id: 'emp-tech',
    campus_id: 'cmp-tech-cdmx',
    pipeline_type: 'corporate_recruitment',
    stage: 'registered',
    tutor_first_name: 'Sebastián',
    tutor_last_name_1: 'Ruiz',
    tutor_last_name_2: 'Calderón',
    tutor_last_name: 'Ruiz Calderón',
    tutor_phone: '55 2233 4455',
    tutor_email: 'sebastian.ruiz@devops.cloud',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'linkedin',
    source_detail: 'Campaña Global Cloud Platform & Kubernetes Engineers',
    lead_score: 91,
    assigned_to: 'recruiter-tech-1',
    assigned_to_name: 'Mtro. Alejandro Ramos (Head of Engineering)',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Ingeniero de Plataforma con 7 años en microservicios, Terraform y orquestación multi-cloud en entornos de alta concurrencia.',
    created_at: '2026-09-22T08:00:00Z',
    updated_at: '2026-09-23T09:30:00Z',
    candidates_count: 1,
    documents_complete_percent: 55,
    days_in_current_stage: 1,
    campus_name: 'Innovation Center CDMX Polanco',
    proposed_salary: '$72,000 MXN / mes',
    department: 'Cloud Platform & DevOps Enterprise',
    recruiter_name: 'Mtro. Alejandro Ramos',
    recruiter_title: 'Head of Engineering & Cloud Ops',
  },
  {
    id: 'lead-tech-002',
    school_id: 'emp-tech',
    campus_id: 'cmp-tech-gdl',
    pipeline_type: 'corporate_recruitment',
    stage: 'tour_scheduled',
    tutor_first_name: 'Karla Daniela',
    tutor_last_name_1: 'Peña',
    tutor_last_name_2: 'Solís',
    tutor_last_name: 'Peña Solís',
    tutor_phone: '33 9988 1122',
    tutor_email: 'karla.pena@mlops.ai',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'headhunting',
    source_detail: 'Headhunting Especializado en MLOps & Arquitectura de IA',
    lead_score: 96,
    assigned_to: 'recruiter-tech-1',
    assigned_to_name: 'Mtro. Alejandro Ramos',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Entrevista técnica profunda agendada sobre optimización de inferencia en clusters GPU y flujos CI/CD de modelos fundacionales.',
    created_at: '2026-09-21T10:00:00Z',
    updated_at: '2026-09-23T12:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 75,
    days_in_current_stage: 1,
    campus_name: 'Tech Hub Guadalajara (Silicon Valley MX)',
    proposed_salary: '$85,000 MXN / mes',
    department: 'AI Research Lab & MLOps Pipelines',
    recruiter_name: 'Dra. Sofía Mendoza Valdés',
    recruiter_title: 'Lead AI Scientist & Advisor',
  },
  {
    id: 'lead-tech-003',
    school_id: 'emp-tech',
    campus_id: 'cmp-tech-gdl',
    pipeline_type: 'corporate_recruitment',
    stage: 'evaluation',
    tutor_first_name: 'Héctor',
    tutor_last_name_1: 'Cárdenas',
    tutor_last_name_2: 'Mora',
    tutor_last_name: 'Cárdenas Mora',
    tutor_phone: '33 4455 6677',
    tutor_email: 'hector.cardenas@fullstack.io',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'job_board',
    source_detail: 'Portal Tech Careers Guadalajara',
    lead_score: 93,
    assigned_to: 'recruiter-tech-1',
    assigned_to_name: 'Mtro. Alejandro Ramos',
    priority: 'warm',
    referral_incentive_applied: false,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Resolvió reto técnico de concurrencia y streaming gRPC con 96% de precisión de código y cero defectos de memoria.',
    created_at: '2026-09-18T14:00:00Z',
    updated_at: '2026-09-23T15:30:00Z',
    candidates_count: 1,
    documents_complete_percent: 85,
    days_in_current_stage: 2,
    campus_name: 'Tech Hub Guadalajara (Silicon Valley MX)',
    proposed_salary: '$78,000 MXN / mes',
    department: 'Core Backend & Distributed Systems',
    recruiter_name: 'Mtro. Alejandro Ramos',
    recruiter_title: 'Head of Engineering & Cloud Ops',
  },
  {
    id: 'lead-tech-004',
    school_id: 'emp-tech',
    campus_id: 'cmp-tech-cdmx',
    pipeline_type: 'corporate_recruitment',
    stage: 'reservation',
    tutor_first_name: 'Diana Marcela',
    tutor_last_name_1: 'Montes',
    tutor_last_name_2: 'Parra',
    tutor_last_name: 'Montes Parra',
    tutor_phone: '55 6677 8899',
    tutor_email: 'diana.montes@dataarchitect.mx',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'internal_referral',
    source_detail: 'Referida por Staff Data Engineer del equipo CDMX',
    lead_score: 95,
    assigned_to: 'recruiter-tech-1',
    assigned_to_name: 'Mtro. Alejandro Ramos',
    priority: 'hot',
    referral_incentive_applied: true,
    outcome: null,
    target_academic_year: '2026-2027',
    notes: 'Carta oferta firmada por la candidata. Incluye bono de contratación (signing bonus) y esquema de trabajo híbrido en Polanco.',
    created_at: '2026-09-16T11:00:00Z',
    updated_at: '2026-09-23T17:30:00Z',
    candidates_count: 1,
    documents_complete_percent: 95,
    days_in_current_stage: 1,
    campus_name: 'Innovation Center CDMX Polanco',
    proposed_salary: '$82,000 MXN / mes',
    department: 'Data Engineering & Big Data Architecture',
    recruiter_name: 'Mtro. Alejandro Ramos',
    recruiter_title: 'Head of Engineering & Cloud Ops',
  },
  {
    id: 'lead-tech-005',
    school_id: 'emp-tech',
    campus_id: 'cmp-tech-gdl',
    pipeline_type: 'corporate_recruitment',
    stage: 'enrolled',
    tutor_first_name: 'Rodrigo',
    tutor_last_name_1: 'Téllez',
    tutor_last_name_2: 'Villegas',
    tutor_last_name: 'Téllez Villegas',
    tutor_phone: '33 1122 3344',
    tutor_email: 'rodrigo.tellez@innovasoft.ai',
    tutor_relationship: 'Candidato Titular',
    source_channel: 'linkedin',
    source_detail: 'Incorporación Estratégica para Liderazgo del Laboratorio de IA',
    lead_score: 100,
    assigned_to: 'recruiter-tech-1',
    assigned_to_name: 'Mtro. Alejandro Ramos',
    priority: 'hot',
    referral_incentive_applied: false,
    outcome: 'enrolled',
    target_academic_year: '2026-2027',
    notes: 'Onboarding completado al 100%. Acceso a entornos de producción, VPN enterprise y contrato laboral registrado ante la autoridad laboral.',
    created_at: '2026-09-12T09:00:00Z',
    updated_at: '2026-09-22T16:00:00Z',
    candidates_count: 1,
    documents_complete_percent: 100,
    days_in_current_stage: 2,
    campus_name: 'Tech Hub Guadalajara (Silicon Valley MX)',
    proposed_salary: '$95,000 MXN / mes',
    department: 'AI Research Lab & Model Optimization',
    recruiter_name: 'Dra. Sofía Mendoza Valdés',
    recruiter_title: 'Lead AI Scientist & Advisor',
  },
];

// ============================================================
// CANDIDATOS (Hijos asociados a leads)
// ============================================================

export const CRM_CANDIDATES_SEED: CrmLeadCandidate[] = [
  {
    id: 'cand-001', lead_id: 'lead-001',
    first_name: 'Sofía Valentina',
    last_name_1: 'Reyes',
    last_name_2: 'Gutiérrez',
    last_name: 'Reyes Gutiérrez',
    birth_date: '2019-03-15', gender: 'F',
    target_level: 'primaria', target_grade: '2°', target_group: 'A',
    current_school_name: 'Colegio Montessori del Valle', current_school_grade: '1°',
    evaluation_status: 'approved', evaluation_date: '2026-09-19',
    evaluation_result: 'Dictamen favorable. Nivel de lectura arriba del promedio para su edad.',
    evaluation_score: 92,
    scholarship_type: undefined, scholarship_percent: 0,
    status: 'active', created_at: '2026-09-20T10:30:00Z', updated_at: '2026-09-22T14:00:00Z',
  },
  {
    id: 'cand-002', lead_id: 'lead-002',
    first_name: 'Diego Alejandro',
    last_name_1: 'Montes',
    last_name_2: 'Villanueva',
    last_name: 'Montes Villanueva',
    birth_date: '2011-07-22', gender: 'M',
    target_level: 'preparatoria', target_grade: '1° Semestre',
    current_school_name: 'Secundaria Técnica #45', current_school_grade: '3°',
    evaluation_status: 'pending',
    scholarship_type: 'corporate_agreement', scholarship_percent: 10,
    status: 'active', created_at: '2026-09-21T09:00:00Z', updated_at: '2026-09-22T16:30:00Z',
  },
  {
    id: 'cand-003', lead_id: 'lead-003',
    first_name: 'Valentina',
    last_name_1: 'Garza',
    last_name_2: 'Morales',
    last_name: 'Garza Morales',
    birth_date: '2022-11-08', gender: 'F',
    target_level: 'preescolar', target_grade: 'Kínder 3',
    evaluation_status: 'approved', evaluation_date: '2026-09-17',
    evaluation_result: 'Excelente desarrollo psicomotriz y socioemocional.',
    evaluation_score: 95,
    enrolled_student_id: 'stu-garza-001', enrolled_at: '2026-09-20T11:00:00Z',
    scholarship_percent: 0,
    status: 'enrolled', created_at: '2026-09-15T08:00:00Z', updated_at: '2026-09-20T11:00:00Z',
  },
  {
    id: 'cand-004', lead_id: 'lead-004',
    first_name: 'Renata Sofía', last_name: 'Cordero',
    birth_date: '2020-05-30', gender: 'F',
    target_level: 'primaria', target_grade: '1°',
    current_school_name: 'Jardín de Niños Rayito de Sol', current_school_grade: 'Kínder 3',
    evaluation_status: 'scheduled', evaluation_date: '2026-09-25',
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-20T11:00:00Z', updated_at: '2026-09-22T09:00:00Z',
  },
  {
    id: 'cand-005', lead_id: 'lead-005',
    first_name: 'Mateo Emiliano', last_name: 'Albarrán',
    birth_date: '2013-01-10', gender: 'M',
    target_level: 'secundaria', target_grade: '1°',
    current_school_name: 'Primaria Particular Cervantes', current_school_grade: '6°',
    evaluation_status: 'approved', evaluation_date: '2026-09-21',
    evaluation_result: 'Dictamen favorable para programa Cambridge KET.',
    evaluation_score: 88,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-18T14:00:00Z', updated_at: '2026-09-22T10:00:00Z',
  },
  {
    id: 'cand-006', lead_id: 'lead-006',
    first_name: 'Leonardo Daniel', last_name: 'Pineda',
    birth_date: '2012-08-05', gender: 'M',
    target_level: 'secundaria', target_grade: '3°', target_group: 'B',
    current_school_name: 'Secundaria Federal #12 Ecatepec', current_school_grade: '2°',
    evaluation_status: 'approved',
    scholarship_type: 'academic', scholarship_percent: 15,
    scholarship_approved_by: 'dir-sancristobal',
    scholarship_approved_at: '2026-09-21T16:00:00Z',
    status: 'active', created_at: '2026-09-19T09:30:00Z', updated_at: '2026-09-22T15:00:00Z',
  },
  {
    id: 'cand-007', lead_id: 'lead-007',
    first_name: 'Camila', last_name: 'Navarro Ruiz',
    birth_date: '2015-12-01', gender: 'F',
    target_level: 'primaria', target_grade: '5°',
    current_school_name: 'Colegio Anglo Americano', current_school_grade: '4°',
    evaluation_status: 'pending',
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-22T08:00:00Z', updated_at: '2026-09-22T08:00:00Z',
  },
  {
    id: 'cand-008', lead_id: 'lead-008',
    first_name: 'Emiliano', last_name: 'Carrillo Treviño',
    birth_date: '2023-04-18', gender: 'M',
    target_level: 'preescolar', target_grade: 'Kínder 2',
    evaluation_status: 'approved', evaluation_date: '2026-09-20',
    evaluation_result: 'Entrevista aprobada con felicitaciones de coordinación.',
    scholarship_type: 'staff_child', scholarship_percent: 20,
    status: 'active', created_at: '2026-09-17T10:00:00Z', updated_at: '2026-09-22T13:00:00Z',
  },
  // Lead-009 tiene 2 hijos (hermanos)
  {
    id: 'cand-009a', lead_id: 'lead-009',
    first_name: 'Bruno Alexander', last_name: 'Ortiz',
    birth_date: '2014-06-12', gender: 'M',
    target_level: 'secundaria', target_grade: '2°',
    current_school_name: 'Secundaria Pública #8', current_school_grade: '1°',
    evaluation_status: 'pending',
    scholarship_type: 'siblings', scholarship_percent: 5,
    status: 'active', created_at: '2026-09-23T09:00:00Z', updated_at: '2026-09-23T09:00:00Z',
  },
  {
    id: 'cand-009b', lead_id: 'lead-009',
    first_name: 'Isabella', last_name: 'Ortiz',
    birth_date: '2017-02-28', gender: 'F',
    target_level: 'primaria', target_grade: '4°',
    current_school_name: 'Primaria Pública Benito Juárez', current_school_grade: '3°',
    evaluation_status: 'pending',
    scholarship_type: 'siblings', scholarship_percent: 5,
    status: 'active', created_at: '2026-09-23T09:00:00Z', updated_at: '2026-09-23T09:00:00Z',
  },
  // Reinscripción
  {
    id: 'cand-012a', lead_id: 'lead-012',
    first_name: 'Andrés', last_name: 'Domínguez',
    birth_date: '2016-09-01', gender: 'M',
    target_level: 'primaria', target_grade: '5°',
    evaluation_status: 'waived',
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-15T09:00:00Z', updated_at: '2026-09-20T09:00:00Z',
  },
  {
    id: 'cand-012b', lead_id: 'lead-012',
    first_name: 'Mariana', last_name: 'Domínguez',
    birth_date: '2018-03-14', gender: 'F',
    target_level: 'primaria', target_grade: '3°',
    evaluation_status: 'waived',
    scholarship_type: 'siblings', scholarship_percent: 5,
    status: 'active', created_at: '2026-09-15T09:00:00Z', updated_at: '2026-09-20T09:00:00Z',
  },

  // --- CANDIDATOS DEMOSTRACIÓN (10 CASOS) ---
  {
    id: 'cand-013', lead_id: 'lead-013',
    first_name: 'Sebastián',
    last_name_1: 'Treviño',
    last_name_2: 'Garza',
    last_name: 'Treviño Garza',
    birth_date: '2019-08-14', gender: 'M',
    curp: 'TEGS190814HNLXXX01',
    target_level: 'primaria', target_grade: '2°',
    current_school_name: 'Colegio San Patricio Monterrey',
    evaluation_status: 'pending',
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-24T05:30:00Z', updated_at: '2026-09-24T05:30:00Z',
  },
  {
    id: 'cand-014', lead_id: 'lead-014',
    first_name: 'Regina',
    last_name_1: 'Ibarra',
    last_name_2: 'Navarrete',
    last_name: 'Ibarra Navarrete',
    birth_date: '2022-04-10', gender: 'F',
    curp: 'IANR220410MDFXXX02',
    target_level: 'preescolar', target_grade: '2°',
    current_school_name: 'Gymboree Pedregal',
    evaluation_status: 'pending',
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-23T16:00:00Z', updated_at: '2026-09-24T03:00:00Z',
  },
  {
    id: 'cand-015', lead_id: 'lead-015',
    first_name: 'Mateo',
    last_name_1: 'Alcocer',
    last_name_2: 'Cantú',
    last_name: 'Alcocer Cantú',
    birth_date: '2013-11-22', gender: 'M',
    curp: 'AOCM131122HDFXXX03',
    target_level: 'secundaria', target_grade: '2°',
    current_school_name: 'Instituto Cumbres México',
    evaluation_status: 'scheduled',
    evaluation_date: '2026-09-26T10:30:00Z',
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-22T12:00:00Z', updated_at: '2026-09-23T18:00:00Z',
  },
  {
    id: 'cand-016', lead_id: 'lead-016',
    first_name: 'Emiliano',
    last_name_1: 'Zepeda',
    last_name_2: 'Cuéllar',
    last_name: 'Zepeda Cuéllar',
    birth_date: '2010-06-18', gender: 'M',
    curp: 'ZECE100618HDFXXX04',
    target_level: 'preparatoria', target_grade: '1°',
    current_school_name: 'Secundaria Técnica 14',
    evaluation_status: 'pending',
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-21T10:00:00Z', updated_at: '2026-09-23T11:00:00Z',
  },
  {
    id: 'cand-017', lead_id: 'lead-017',
    first_name: 'Valentina',
    last_name_1: 'Baeza',
    last_name_2: 'Orozco',
    last_name: 'Baeza Orozco',
    birth_date: '2017-02-05', gender: 'F',
    curp: 'BAOV170205MDFXXX05',
    target_level: 'primaria', target_grade: '4°',
    current_school_name: 'Colegio Regina',
    evaluation_status: 'approved',
    evaluation_date: '2026-09-22T10:00:00Z',
    evaluation_result: 'Excelente desempeño cognitivo y madurez. Puntaje diagnóstico: 95/100.',
    evaluation_score: 95,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-19T09:30:00Z', updated_at: '2026-09-23T15:00:00Z',
  },
  {
    id: 'cand-018a', lead_id: 'lead-018',
    first_name: 'Santiago',
    last_name_1: 'Mendoza',
    last_name_2: 'Carrillo',
    last_name: 'Mendoza Carrillo',
    birth_date: '2016-05-12', gender: 'M',
    curp: 'MECS160512HDFXXX06',
    target_level: 'primaria', target_grade: '5°',
    current_school_name: 'Instituto Moderno Americano',
    evaluation_status: 'approved',
    evaluation_date: '2026-09-22T09:00:00Z',
    evaluation_result: 'Aprobado satisfactoriamente con colocación en inglés avanzado B2.',
    evaluation_score: 90,
    scholarship_type: 'corporate_agreement', scholarship_percent: 15,
    status: 'active', created_at: '2026-09-20T11:00:00Z', updated_at: '2026-09-23T17:00:00Z',
  },
  {
    id: 'cand-018b', lead_id: 'lead-018',
    first_name: 'Camila',
    last_name_1: 'Mendoza',
    last_name_2: 'Carrillo',
    last_name: 'Mendoza Carrillo',
    birth_date: '2019-10-30', gender: 'F',
    curp: 'MECC191030MDFXXX07',
    target_level: 'primaria', target_grade: '2°',
    current_school_name: 'Instituto Moderno Americano',
    evaluation_status: 'approved',
    evaluation_date: '2026-09-22T10:00:00Z',
    evaluation_result: 'Madurez socioemocional y lectoescritura afianzada. Aprobada.',
    evaluation_score: 88,
    scholarship_type: 'corporate_agreement', scholarship_percent: 15,
    status: 'active', created_at: '2026-09-20T11:00:00Z', updated_at: '2026-09-23T17:00:00Z',
  },
  {
    id: 'cand-019', lead_id: 'lead-019',
    first_name: 'Leonardo',
    last_name_1: 'Morales',
    last_name_2: 'Del Río',
    last_name: 'Morales Del Río',
    birth_date: '2014-07-25', gender: 'M',
    curp: 'MODL140725HDFXXX08',
    target_level: 'secundaria', target_grade: '1°',
    current_school_name: 'Colegio Cristóbal Colón',
    evaluation_status: 'approved',
    evaluation_date: '2026-09-21T11:00:00Z',
    evaluation_result: 'Promedio académico 9.8 en boleta anterior. Beca de excelencia autorizada.',
    evaluation_score: 98,
    scholarship_type: 'excellence', scholarship_percent: 20,
    status: 'active', created_at: '2026-09-18T10:00:00Z', updated_at: '2026-09-23T19:00:00Z',
  },
  {
    id: 'cand-020', lead_id: 'lead-020',
    first_name: 'Matías',
    last_name_1: 'Villalobos',
    last_name_2: 'Cárdenas',
    last_name: 'Villalobos Cárdenas',
    birth_date: '2024-01-15', gender: 'M',
    curp: 'VICM240115HDFXXX09',
    target_level: 'maternal', target_grade: '1°',
    evaluation_status: 'waived',
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-16T12:00:00Z', updated_at: '2026-09-23T20:00:00Z',
  },
  {
    id: 'cand-021', lead_id: 'lead-021',
    first_name: 'Luciana',
    last_name_1: 'Salgado',
    last_name_2: 'Noriega',
    last_name: 'Salgado Noriega',
    birth_date: '2020-03-08', gender: 'F',
    curp: 'SANL200308MDFXXX10',
    target_level: 'primaria', target_grade: '1°',
    current_school_name: 'Kinder Cedros',
    evaluation_status: 'approved',
    evaluation_date: '2026-09-15T09:30:00Z',
    evaluation_result: 'Evaluación y expediente completados al 100%. Inscripción formalizada.',
    evaluation_score: 96,
    scholarship_percent: 0,
    status: 'enrolled', created_at: '2026-09-12T08:30:00Z', updated_at: '2026-09-22T13:00:00Z',
  },
  {
    id: 'cand-022', lead_id: 'lead-022',
    first_name: 'Bruno',
    last_name_1: 'Obregón',
    last_name_2: 'Téllez',
    last_name: 'Obregón Téllez',
    birth_date: '2012-09-19', gender: 'M',
    curp: 'OETB120919HDFXXX11',
    target_level: 'secundaria', target_grade: '3°',
    current_school_name: 'Secundaria Diurna 45',
    evaluation_status: 'pending',
    scholarship_percent: 0,
    status: 'declined', created_at: '2026-09-14T09:00:00Z', updated_at: '2026-09-23T14:00:00Z',
  },

  // --- CANDIDATOS CORPORATIVOS: BMW GROUP MÉXICO (emp-bmw) ---
  {
    id: 'cand-bmw-001', lead_id: 'lead-bmw-001',
    first_name: 'Daniel', last_name_1: 'Zavala', last_name_2: 'Ríos', last_name: 'Zavala Ríos',
    birth_date: '1994-06-12', gender: 'M',
    target_level: 'corporativo', target_grade: 'Senior Specialist',
    position_title: 'Especialista en Robótica KUKA & Celdas de Soldadura',
    department: 'Ensamble y Robótica Industrial',
    proposed_salary: '$48,000 MXN / mes',
    technical_score: 94,
    certifications: ['KUKA SafeOperation KRC4', 'Norma ISO 10218-1 Seguridad Robótica'],
    evaluation_status: 'scheduled',
    evaluation_result: 'Perfil técnico de alta especialización en cinemática directa y programación offline.',
    evaluation_score: 94,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-22T08:30:00Z', updated_at: '2026-09-23T10:00:00Z',
  },
  {
    id: 'cand-bmw-002', lead_id: 'lead-bmw-002',
    first_name: 'Paulina', last_name_1: 'Morales', last_name_2: 'Dávila', last_name: 'Morales Dávila',
    birth_date: '1992-09-18', gender: 'F',
    target_level: 'corporativo', target_grade: 'Lead Auditor',
    position_title: 'Especialista en Calidad & Protocolos ISO 14001',
    department: 'Seguridad Industrial & Calidad ISO',
    proposed_salary: '$52,000 MXN / mes',
    technical_score: 91,
    certifications: ['Auditor Líder ISO 14001:2015', 'Certificación IATF 16949'],
    evaluation_status: 'approved',
    evaluation_result: 'Dictamen favorable en auditoría de procesos de manufactura automotriz limpia.',
    evaluation_score: 91,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-21T11:00:00Z', updated_at: '2026-09-23T14:30:00Z',
  },
  {
    id: 'cand-bmw-003', lead_id: 'lead-bmw-003',
    first_name: 'Andrea', last_name_1: 'Pantoja', last_name_2: 'Cruz', last_name: 'Pantoja Cruz',
    birth_date: '1990-03-24', gender: 'F',
    target_level: 'corporativo', target_grade: 'Principal Engineer',
    position_title: 'Ingeniera de Ensamble Tren Motriz Eléctrico',
    department: 'Centro de Ensamble Baterías Alto Voltaje',
    proposed_salary: '$54,000 MXN / mes',
    technical_score: 96,
    certifications: ['DGUV 200-005 Nivel 3 Alto Voltaje', 'Certificación ECE R100'],
    evaluation_status: 'scheduled',
    evaluation_result: 'Experta en aislamiento galvánico y módulos de enfriamiento de baterías de tracción.',
    evaluation_score: 96,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-20T09:00:00Z', updated_at: '2026-09-23T16:00:00Z',
  },
  {
    id: 'cand-bmw-004', lead_id: 'lead-bmw-004',
    first_name: 'Mauricio', last_name_1: 'Garza', last_name_2: 'Treviño', last_name: 'Garza Treviño',
    birth_date: '1988-11-05', gender: 'M',
    target_level: 'corporativo', target_grade: 'Líder Técnico',
    position_title: 'Líder Técnico de Ensamble & ISO 45001',
    department: 'Ensamble y Robótica Industrial',
    proposed_salary: '$58,000 MXN / mes',
    technical_score: 93,
    certifications: ['ISO 45001 Seguridad y Salud en el Trabajo', 'Six Sigma Green Belt'],
    evaluation_status: 'approved',
    evaluation_result: 'Aprobó prueba técnica en celda KUKA real y evaluación psicométrica gerencial con 93/100.',
    evaluation_score: 93,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-18T10:00:00Z', updated_at: '2026-09-23T11:00:00Z',
  },
  {
    id: 'cand-bmw-005', lead_id: 'lead-bmw-005',
    first_name: 'Claudia', last_name_1: 'Morales', last_name_2: 'Ortiz', last_name: 'Morales Ortiz',
    birth_date: '1993-07-14', gender: 'F',
    target_level: 'corporativo', target_grade: 'Supervisora Senior',
    position_title: 'Supervisora de Logística JIT & Cadena Automotriz',
    department: 'Logística & Cadena de Suministro JIT',
    proposed_salary: '$45,000 MXN / mes',
    technical_score: 89,
    certifications: ['APICS Certified Supply Chain Professional (CSCP)', 'Lean Logistics'],
    evaluation_status: 'approved',
    evaluation_result: 'Validada por la Gerencia de Operaciones. Propuesta económica en revisión de la candidata.',
    evaluation_score: 89,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-17T14:00:00Z', updated_at: '2026-09-23T17:00:00Z',
  },
  {
    id: 'cand-bmw-006', lead_id: 'lead-bmw-006',
    first_name: 'Fernando', last_name_1: 'Schmidt', last_name_2: 'Keller', last_name: 'Schmidt Keller',
    birth_date: '1987-02-28', gender: 'M',
    target_level: 'corporativo', target_grade: 'Staff Architect',
    position_title: 'Arquitecto de Telemetría Vehicular & Baterías',
    department: 'Investigación & Desarrollo de Baterías',
    proposed_salary: '$65,000 MXN / mes',
    technical_score: 98,
    certifications: ['CAN Bus Protocol Specialist', 'AUTOSAR Architecture Master'],
    evaluation_status: 'approved',
    evaluation_result: 'Dictamen de contratación unánime. Incorporado a la nómina de Planta San Luis Potosí.',
    evaluation_score: 98,
    enrolled_student_id: 'std-bmw-06',
    enrolled_at: '2026-09-22T15:00:00Z',
    scholarship_percent: 0,
    status: 'enrolled', created_at: '2026-09-10T08:00:00Z', updated_at: '2026-09-22T15:00:00Z',
  },
  {
    id: 'cand-bmw-007', lead_id: 'lead-bmw-007',
    first_name: 'Gabriel', last_name_1: 'Ramos', last_name_2: 'Lozano', last_name: 'Ramos Lozano',
    birth_date: '1995-12-03', gender: 'M',
    target_level: 'corporativo', target_grade: 'Coordinador',
    position_title: 'Coordinador de Postventa & Fidelización Santa Fe',
    department: 'Comercial & Postventa Santa Fe',
    proposed_salary: '$42,000 MXN / mes',
    technical_score: 87,
    certifications: ['Customer Experience Excellence', 'CRM Automotive Specialist'],
    evaluation_status: 'scheduled',
    evaluation_score: 87,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-22T10:00:00Z', updated_at: '2026-09-23T12:00:00Z',
  },
  {
    id: 'cand-bmw-008', lead_id: 'lead-bmw-008',
    first_name: 'Jorge Alberto', last_name_1: 'Rivas', last_name_2: 'Villarreal', last_name: 'Rivas Villarreal',
    birth_date: '1998-05-19', gender: 'M',
    target_level: 'corporativo', target_grade: 'Técnico Especialista',
    position_title: 'Técnico de Mantenimiento Preventivo Celdas KUKA',
    department: 'Mantenimiento Preventivo Celdas KUKA',
    proposed_salary: '$34,000 MXN / mes',
    technical_score: 90,
    certifications: ['Técnico Superior Universitario Mecatrónica', 'Manejo de Servomotores'],
    evaluation_status: 'approved',
    evaluation_result: 'Aprobó evaluación de habilidades prácticas de diagnóstico electromecánico.',
    evaluation_score: 90,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-15T09:30:00Z', updated_at: '2026-09-23T18:00:00Z',
  },

  // --- CANDIDATOS CORPORATIVOS: GRUPO COMERCIAL VANGUARDIA RETAIL (emp-ventas) ---
  {
    id: 'cand-ventas-001', lead_id: 'lead-ventas-001',
    first_name: 'Valeria', last_name_1: 'Santos', last_name_2: 'Orozco', last_name: 'Santos Orozco',
    birth_date: '1991-08-20', gender: 'F',
    target_level: 'corporativo', target_grade: 'Gerencia',
    position_title: 'Gerente de Compras Omnicanal & Retail Analytics',
    department: 'Compras Corporativas & Retail Omnicanal',
    proposed_salary: '$42,000 MXN / mes',
    technical_score: 88,
    certifications: ['Category Management Certified', 'Retail Analytics Professional'],
    evaluation_status: 'scheduled',
    evaluation_score: 88,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-22T09:00:00Z', updated_at: '2026-09-23T11:00:00Z',
  },
  {
    id: 'cand-ventas-002', lead_id: 'lead-ventas-002',
    first_name: 'Rodrigo', last_name_1: 'Villarreal', last_name_2: 'Sada', last_name: 'Villarreal Sada',
    birth_date: '1989-10-11', gender: 'M',
    target_level: 'corporativo', target_grade: 'Coordinación Senior',
    position_title: 'Coordinador de Distribución y Flotas CEDIS',
    department: 'Operaciones Logísticas & Flotas CEDIS',
    proposed_salary: '$36,000 MXN / mes',
    technical_score: 91,
    certifications: ['Gestión de Flotas y Telemetría GPS', 'Normativa SCT de Transporte'],
    evaluation_status: 'scheduled',
    evaluation_score: 91,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-20T10:00:00Z', updated_at: '2026-09-23T13:00:00Z',
  },
  {
    id: 'cand-ventas-003', lead_id: 'lead-ventas-003',
    first_name: 'Brenda', last_name_1: 'Covarrubias', last_name_2: 'Lara', last_name: 'Covarrubias Lara',
    birth_date: '1993-04-16', gender: 'F',
    target_level: 'corporativo', target_grade: 'Supervisión',
    position_title: 'Supervisora de Operaciones WMS y Logística Inversa',
    department: 'Almacén & Distribución Occidente',
    proposed_salary: '$38,000 MXN / mes',
    technical_score: 89,
    certifications: ['SAP Warehouse Management', 'Lean Warehousing'],
    evaluation_status: 'approved',
    evaluation_result: 'Aprobó caso práctico de reubicación y optimización de picking.',
    evaluation_score: 89,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-19T08:00:00Z', updated_at: '2026-09-23T15:00:00Z',
  },
  {
    id: 'cand-ventas-004', lead_id: 'lead-ventas-004',
    first_name: 'Carlos', last_name_1: 'Alcocer', last_name_2: 'Ramos', last_name: 'Alcocer Ramos',
    birth_date: '1986-07-29', gender: 'M',
    target_level: 'corporativo', target_grade: 'Key Account Manager',
    position_title: 'Key Account Manager Cuentas Clave Retail',
    department: 'Fuerza Comercial KAM Cuentas Clave',
    proposed_salary: '$46,000 MXN / mes',
    technical_score: 93,
    certifications: ['Negociación Estratégica Método Harvard', 'B2B Sales Executive'],
    evaluation_status: 'approved',
    evaluation_result: 'Propuesta económica entregada. Excelente trayectoria comercial con cadenas departamentales.',
    evaluation_score: 93,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-17T11:00:00Z', updated_at: '2026-09-23T16:00:00Z',
  },
  {
    id: 'cand-ventas-005', lead_id: 'lead-ventas-005',
    first_name: 'Mónica', last_name_1: 'Terán', last_name_2: 'Sepúlveda', last_name: 'Terán Sepúlveda',
    birth_date: '1985-01-12', gender: 'F',
    target_level: 'corporativo', target_grade: 'Subdirección',
    position_title: 'Subdirectora de Experiencia del Cliente & Postventa',
    department: 'Dirección de Experiencia del Cliente',
    proposed_salary: '$52,000 MXN / mes',
    technical_score: 97,
    certifications: ['Net Promoter Score (NPS) Master', 'Customer Journey Mapping'],
    evaluation_status: 'approved',
    evaluation_result: 'Aprobación del comité ejecutivo. Integrada a nómina activa de CEDIS Monterrey.',
    evaluation_score: 97,
    enrolled_student_id: 'std-ventas-05',
    enrolled_at: '2026-09-22T14:00:00Z',
    scholarship_percent: 0,
    status: 'enrolled', created_at: '2026-09-11T09:00:00Z', updated_at: '2026-09-22T14:00:00Z',
  },
  {
    id: 'cand-ventas-006', lead_id: 'lead-ventas-006',
    first_name: 'Andrés', last_name_1: 'Peñaloza', last_name_2: 'Guzmán', last_name: 'Peñaloza Guzmán',
    birth_date: '1996-11-22', gender: 'M',
    target_level: 'corporativo', target_grade: 'Supervisión',
    position_title: 'Supervisor de Inventarios Cíclicos & Merma',
    department: 'Inventarios Cíclicos & Control de Pérdidas',
    proposed_salary: '$32,000 MXN / mes',
    technical_score: 86,
    certifications: ['Auditoría Operativa de Almacenes', 'Control de Mermas'],
    evaluation_status: 'approved',
    evaluation_score: 86,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-16T12:00:00Z', updated_at: '2026-09-23T18:00:00Z',
  },

  // --- CANDIDATOS CORPORATIVOS: INNOVASOFT TECH DYNAMICS (emp-tech) ---
  {
    id: 'cand-tech-001', lead_id: 'lead-tech-001',
    first_name: 'Sebastián', last_name_1: 'Ruiz', last_name_2: 'Calderón', last_name: 'Ruiz Calderón',
    birth_date: '1992-06-08', gender: 'M',
    target_level: 'corporativo', target_grade: 'Senior Engineer',
    position_title: 'Senior DevOps & Cloud Platform Engineer',
    department: 'Cloud Platform & DevOps Enterprise',
    proposed_salary: '$72,000 MXN / mes',
    technical_score: 92,
    certifications: ['Certified Kubernetes Administrator (CKA)', 'HashiCorp Terraform Associate'],
    evaluation_status: 'scheduled',
    evaluation_score: 92,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-22T08:00:00Z', updated_at: '2026-09-23T09:30:00Z',
  },
  {
    id: 'cand-tech-002', lead_id: 'lead-tech-002',
    first_name: 'Karla Daniela', last_name_1: 'Peña', last_name_2: 'Solís', last_name: 'Peña Solís',
    birth_date: '1990-12-14', gender: 'F',
    target_level: 'corporativo', target_grade: 'Staff Specialist',
    position_title: 'Staff MLOps & AI Deployment Specialist',
    department: 'AI Research Lab & MLOps Pipelines',
    proposed_salary: '$85,000 MXN / mes',
    technical_score: 96,
    certifications: ['Kubeflow End-to-End Specialist', 'NVIDIA TensorRT Optimization'],
    evaluation_status: 'scheduled',
    evaluation_score: 96,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-21T10:00:00Z', updated_at: '2026-09-23T12:00:00Z',
  },
  {
    id: 'cand-tech-003', lead_id: 'lead-tech-003',
    first_name: 'Héctor', last_name_1: 'Cárdenas', last_name_2: 'Mora', last_name: 'Cárdenas Mora',
    birth_date: '1989-08-30', gender: 'M',
    target_level: 'corporativo', target_grade: 'Principal Engineer',
    position_title: 'Fullstack Principal & Golang Microservices',
    department: 'Core Backend & Distributed Systems',
    proposed_salary: '$78,000 MXN / mes',
    technical_score: 94,
    certifications: ['Go Professional Certified', 'Distributed Systems Architecture'],
    evaluation_status: 'approved',
    evaluation_result: 'Resolución sobresaliente de prueba de arquitectura distribuida concurrente.',
    evaluation_score: 94,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-18T14:00:00Z', updated_at: '2026-09-23T15:30:00Z',
  },
  {
    id: 'cand-tech-004', lead_id: 'lead-tech-004',
    first_name: 'Diana Marcela', last_name_1: 'Montes', last_name_2: 'Parra', last_name: 'Montes Parra',
    birth_date: '1991-03-05', gender: 'F',
    target_level: 'corporativo', target_grade: 'Data Architect',
    position_title: 'Data Architect & Big Data Distributed Pipelines',
    department: 'Data Engineering & Big Data Architecture',
    proposed_salary: '$82,000 MXN / mes',
    technical_score: 95,
    certifications: ['Apache Spark Certified Developer', 'Data Lakehouse Architect'],
    evaluation_status: 'approved',
    evaluation_result: 'Aprobada por el equipo de datos. Propuesta salarial aceptada.',
    evaluation_score: 95,
    scholarship_percent: 0,
    status: 'active', created_at: '2026-09-16T11:00:00Z', updated_at: '2026-09-23T17:30:00Z',
  },
  {
    id: 'cand-tech-005', lead_id: 'lead-tech-005',
    first_name: 'Rodrigo', last_name_1: 'Téllez', last_name_2: 'Villegas', last_name: 'Téllez Villegas',
    birth_date: '1984-05-17', gender: 'M',
    target_level: 'corporativo', target_grade: 'Lead Scientist',
    position_title: 'Lead AI Scientist & Computer Vision',
    department: 'AI Research Lab & Model Optimization',
    proposed_salary: '$95,000 MXN / mes',
    technical_score: 99,
    certifications: ['PhD in Computer Vision & Robotics', 'Deep Learning Specialization'],
    evaluation_status: 'approved',
    evaluation_result: 'Contratado. Asignado como líder técnico del laboratorio de inteligencia artificial.',
    evaluation_score: 99,
    enrolled_student_id: 'std-tech-05',
    enrolled_at: '2026-09-22T16:00:00Z',
    scholarship_percent: 0,
    status: 'enrolled', created_at: '2026-09-12T09:00:00Z', updated_at: '2026-09-22T16:00:00Z',
  },
];

// ============================================================
// ACTIVIDADES (Bitácora de seguimiento)
// ============================================================

export const CRM_ACTIVITIES_SEED: CrmActivity[] = [
  // Lead-001: Fernando Reyes
  {
    id: 'act-001-a', lead_id: 'lead-001',
    activity_type: 'note', title: 'Registro inicial de prospecto',
    description: 'Prospecto registrado vía recomendación de familia Garza (alumno activo en 4° Primaria Lagos). Interesado en 2° Primaria Bilingüe para su hija Sofía.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-20T10:30:00Z',
  },
  {
    id: 'act-001-b', lead_id: 'lead-001',
    activity_type: 'call', title: 'Llamada de primer contacto',
    description: 'Se contactó al papá Fernando. Muy interesado, viene de Montessori del Valle. Preguntó por programa bilingüe y horarios extendidos. Se agendó tour para el 21 de septiembre.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-20T11:15:00Z',
  },
  {
    id: 'act-001-c', lead_id: 'lead-001',
    activity_type: 'stage_change', title: 'Avance de etapa',
    description: 'Lead avanzó de Registrado a Contacto Efectivo.',
    previous_stage: 'registered', new_stage: 'contacted',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-20T11:16:00Z',
  },
  {
    id: 'act-001-d', lead_id: 'lead-001',
    activity_type: 'tour', title: 'Recorrido por Campus Montes completado',
    description: 'Tour guiado por instalaciones: laboratorio STEAM, biblioteca bilingüe, canchas techadas y comedor. El papá quedó impresionado con el programa de robótica. Se entregó paquete de informes impresos.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-21T10:00:00Z',
  },
  {
    id: 'act-001-e', lead_id: 'lead-001',
    activity_type: 'stage_change', title: 'Avance de etapa',
    previous_stage: 'contacted', new_stage: 'tour_scheduled',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-21T10:05:00Z',
  },
  {
    id: 'act-001-f', lead_id: 'lead-001',
    activity_type: 'evaluation', title: 'Evaluación diagnóstica aplicada y aprobada',
    description: 'Sofía Valentina presentó examen diagnóstico de lectura, matemáticas y socioemocional. Resultado: nivel de lectura arriba del promedio. Recomendación: 2° A Bilingüe sin refuerzo.',
    is_task: false, is_overdue: false,
    created_by: 'staff-psico-ibime-1', created_by_name: 'Psic. Carmen Flores',
    created_at: '2026-09-21T15:00:00Z',
  },
  {
    id: 'act-001-g', lead_id: 'lead-001',
    activity_type: 'whatsapp', title: 'Propuesta económica enviada por WhatsApp',
    description: 'Se envió PDF con desglose de costos: inscripción $8,500 + colegiatura mensual $6,200 + materiales $3,800. Total primer pago: $18,500 MXN.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-22T09:00:00Z',
  },
  {
    id: 'act-001-h', lead_id: 'lead-001',
    activity_type: 'task', title: 'Confirmar pago de inscripción',
    description: 'Llamar al papá Fernando para confirmar si realizó la transferencia SPEI para reservar plaza.',
    is_task: true, scheduled_at: '2026-09-25T10:00:00Z', is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-22T14:00:00Z',
  },
  // Lead-007: Andrea Ruiz (recién registrada — solo 1 actividad)
  {
    id: 'act-007-a', lead_id: 'lead-007',
    activity_type: 'note', title: 'Formulario web recibido',
    description: 'Prospecto ingresó por formulario del sitio web institucional. Interesada en 5° Primaria para su hija Camila. Asesor asignado para llamada de bienvenida.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-4', created_by_name: 'Lic. Daniel Flores',
    created_at: '2026-09-22T08:00:00Z',
  },
  {
    id: 'act-007-b', lead_id: 'lead-007',
    activity_type: 'task', title: 'Llamada de bienvenida',
    description: 'Realizar llamada de primer contacto a la mamá Andrea para presentarse, validar interés y agendar recorrido.',
    is_task: true, scheduled_at: '2026-09-23T10:00:00Z', is_overdue: false,
    created_by: 'staff-adm-ibime-4', created_by_name: 'Lic. Daniel Flores',
    created_at: '2026-09-22T08:05:00Z',
  },

  // --- ACTIVIDADES DE DEMOSTRACIÓN (10 CASOS) ---
  {
    id: 'act-013-a', lead_id: 'lead-013',
    activity_type: 'whatsapp', title: 'Mensaje urgente de WhatsApp recibido',
    description: 'El padre de familia contactó a las 11:30 PM solicitando informes y costos para 2° Primaria. Se mudan de Monterrey en 1 mes.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-24T05:30:00Z',
  },
  {
    id: 'act-013-b', lead_id: 'lead-013',
    activity_type: 'task', title: 'Llamada prioritaria de bienvenida y asesoría',
    description: 'Llamar a primera hora al Lic. Treviño para explicar el modelo bilingüe, validar documentos y agendar recorrido virtual o presencial.',
    is_task: true, scheduled_at: '2026-09-24T09:00:00Z', is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-24T05:35:00Z',
  },
  {
    id: 'act-014-a', lead_id: 'lead-014',
    activity_type: 'call', title: 'Llamada de primer contacto realizada',
    description: 'Se contactó a la mamá Claudia. Muy receptiva. Interesada en horario extendido y talleres vespertinos. Se envió brochure vía WhatsApp.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-2', created_by_name: 'Mtra. Lucía Hernández',
    created_at: '2026-09-24T03:00:00Z',
  },
  {
    id: 'act-015-a', lead_id: 'lead-015',
    activity_type: 'tour', title: 'Tour escolar presencial agendado',
    description: 'Cita confirmada para el viernes a las 10:30 AM. La Dirección Técnica acompañará a la familia por los laboratorios STEAM y canchas deportivas.',
    is_task: true, scheduled_at: '2026-09-26T10:30:00Z', is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-23T18:00:00Z',
  },
  {
    id: 'act-016-a', lead_id: 'lead-016',
    activity_type: 'visit', title: 'Asistencia y registro en Open House CCH',
    description: 'La Dra. Patricia Zepeda y su hijo Emiliano asistieron a la sesión informativa de Preparatoria. Se resolvieron dudas del plan UNAM/CCH.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-23T11:00:00Z',
  },
  {
    id: 'act-017-a', lead_id: 'lead-017',
    activity_type: 'evaluation', title: 'Diagnóstico psicopedagógico y académico aprobado',
    description: 'Valentina obtuvo 95/100 en pensamiento matemático y 98/100 en inglés. La psicóloga escolar emite dictamen altamente favorable.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-23T15:00:00Z',
  },
  {
    id: 'act-018-a', lead_id: 'lead-018',
    activity_type: 'note', title: 'Convenio corporativo BBVA validado',
    description: 'Se validó la constancia laboral de la madre Liliana Carrillo. Aplica 15% de beneficio corporativo en la colegiatura mensual de ambos hermanos.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-2', created_by_name: 'Mtra. Lucía Hernández',
    created_at: '2026-09-23T17:00:00Z',
  },
  {
    id: 'act-019-a', lead_id: 'lead-019',
    activity_type: 'note', title: 'Corrida financiera formal enviada',
    description: 'Se entregó propuesta económica para 1° Secundaria con 20% de beca de excelencia académica. Familia revisando en mesa directiva de presupuesto.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-23T19:00:00Z',
  },
  {
    id: 'act-019-b', lead_id: 'lead-019',
    activity_type: 'task', title: 'Seguimiento a corrida financiera',
    description: 'Llamar al Dr. Morales para dar seguimiento a dudas sobre formas de pago (anualidad vs 10 mensualidades).',
    is_task: true, scheduled_at: '2026-09-25T11:00:00Z', is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-23T19:05:00Z',
  },
  {
    id: 'act-020-a', lead_id: 'lead-020',
    activity_type: 'payment_received', title: 'Anticipo de lugar recibido en caja escolar',
    description: 'Pago de $3,500 MXN en caja escolar para reservar lugar en Maternal A ciclo 2027-2028. Recibo fiscal emitido.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-3', created_by_name: 'Lic. Sofía Alatorre',
    created_at: '2026-09-23T20:00:00Z',
  },
  {
    id: 'act-021-a', lead_id: 'lead-021',
    activity_type: 'enrollment_completed', title: 'Inscripción formalizada y matrícula escolar asignada',
    description: 'Inscripción anual liquidada al 100%. Matrícula MAT-2027-0142 asignada en sistema escolar. Alumna transferida a control académico.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-22T13:00:00Z',
  },
  {
    id: 'act-022-a', lead_id: 'lead-022',
    activity_type: 'call', title: 'Notificación de declinación por cambio de residencia',
    description: 'La madre Daniela informa que la empresa reubicó a su esposo a la planta de Querétaro. Se agradeció el interés y se desearon éxitos.',
    is_task: false, is_overdue: false,
    created_by: 'staff-adm-ibime-1', created_by_name: 'Lic. Mariana Solís',
    created_at: '2026-09-23T14:00:00Z',
  },
];

// ============================================================
// DOCUMENTOS (Expediente de admisión)
// ============================================================

export const CRM_DOCUMENTS_SEED: CrmDocument[] = [
  // Lead-001: 6 de 8 documentos (75%)
  { id: 'doc-001-a', lead_id: 'lead-001', candidate_id: 'cand-001', document_type: 'birth_certificate', document_label: 'Acta de Nacimiento', status: 'verified', verified_by: 'staff-adm-ibime-1', verified_at: '2026-09-21T12:00:00Z', file_name: 'acta_nacimiento_sofia_reyes.pdf', created_at: '2026-09-20T14:00:00Z' },
  { id: 'doc-001-b', lead_id: 'lead-001', candidate_id: 'cand-001', document_type: 'curp_document', document_label: 'CURP', status: 'verified', verified_by: 'staff-adm-ibime-1', verified_at: '2026-09-21T12:05:00Z', file_name: 'curp_sofia_reyes.pdf', created_at: '2026-09-20T14:01:00Z' },
  { id: 'doc-001-c', lead_id: 'lead-001', candidate_id: 'cand-001', document_type: 'vaccination_card', document_label: 'Cartilla de Vacunación', status: 'uploaded', file_name: 'cartilla_sofia_reyes.jpg', created_at: '2026-09-21T09:00:00Z' },
  { id: 'doc-001-d', lead_id: 'lead-001', candidate_id: 'cand-001', document_type: 'previous_school_transcript', document_label: 'Boleta Montessori del Valle', status: 'verified', verified_by: 'staff-adm-ibime-1', verified_at: '2026-09-21T14:00:00Z', file_name: 'boleta_montessori.pdf', created_at: '2026-09-21T08:00:00Z' },
  { id: 'doc-001-e', lead_id: 'lead-001', document_type: 'ine_tutor', document_label: 'INE del Tutor', status: 'verified', verified_by: 'staff-adm-ibime-1', verified_at: '2026-09-21T12:10:00Z', file_name: 'ine_fernando_reyes.pdf', created_at: '2026-09-20T14:02:00Z' },
  { id: 'doc-001-f', lead_id: 'lead-001', candidate_id: 'cand-001', document_type: 'photos', document_label: 'Fotografías', status: 'verified', file_name: 'fotos_sofia.zip', created_at: '2026-09-21T09:30:00Z' },
  { id: 'doc-001-g', lead_id: 'lead-001', document_type: 'proof_of_address', document_label: 'Comprobante de Domicilio', status: 'pending', created_at: '2026-09-20T10:30:00Z' },
  { id: 'doc-001-h', lead_id: 'lead-001', candidate_id: 'cand-001', document_type: 'medical_report', document_label: 'Certificado Médico', status: 'pending', created_at: '2026-09-20T10:30:00Z' },

  // Lead-017: Valentina Baeza (60% completo)
  { id: 'doc-017-a', lead_id: 'lead-017', candidate_id: 'cand-017', document_type: 'birth_certificate', document_label: 'Acta de Nacimiento', status: 'verified', verified_by: 'staff-adm-ibime-1', verified_at: '2026-09-22T11:00:00Z', file_name: 'acta_valentina_baeza.pdf', created_at: '2026-09-20T09:00:00Z' },
  { id: 'doc-017-b', lead_id: 'lead-017', candidate_id: 'cand-017', document_type: 'curp_document', document_label: 'CURP', status: 'verified', verified_by: 'staff-adm-ibime-1', verified_at: '2026-09-22T11:05:00Z', file_name: 'curp_valentina_baeza.pdf', created_at: '2026-09-20T09:01:00Z' },
  { id: 'doc-017-c', lead_id: 'lead-017', candidate_id: 'cand-017', document_type: 'previous_school_transcript', document_label: 'Boleta Oficial SEP Colegio Regina (9.6)', status: 'verified', verified_by: 'staff-adm-ibime-1', verified_at: '2026-09-22T11:10:00Z', file_name: 'boleta_regina_valentina.pdf', created_at: '2026-09-20T09:05:00Z' },

  // Lead-020: Matías Villalobos (85% completo)
  { id: 'doc-020-a', lead_id: 'lead-020', candidate_id: 'cand-020', document_type: 'birth_certificate', document_label: 'Acta de Nacimiento', status: 'verified', verified_by: 'staff-adm-ibime-3', verified_at: '2026-09-23T12:00:00Z', file_name: 'acta_matias_villalobos.pdf', created_at: '2026-09-17T10:00:00Z' },
  { id: 'doc-020-b', lead_id: 'lead-020', candidate_id: 'cand-020', document_type: 'vaccination_card', document_label: 'Cartilla Nacional de Vacunación', status: 'verified', verified_by: 'staff-adm-ibime-3', verified_at: '2026-09-23T12:05:00Z', file_name: 'cartilla_matias.jpg', created_at: '2026-09-17T10:05:00Z' },
  { id: 'doc-020-c', lead_id: 'lead-020', document_type: 'ine_tutor', document_label: 'INE de la Madre', status: 'verified', verified_by: 'staff-adm-ibime-3', verified_at: '2026-09-23T12:10:00Z', file_name: 'ine_andrea_villalobos.pdf', created_at: '2026-09-17T10:10:00Z' },

  // Lead-021: Luciana Salgado (100% formalizada)
  { id: 'doc-021-a', lead_id: 'lead-021', candidate_id: 'cand-021', document_type: 'birth_certificate', document_label: 'Acta de Nacimiento', status: 'verified', verified_by: 'staff-adm-ibime-1', verified_at: '2026-09-21T10:00:00Z', file_name: 'acta_luciana_salgado.pdf', created_at: '2026-09-13T09:00:00Z' },
  { id: 'doc-021-b', lead_id: 'lead-021', candidate_id: 'cand-021', document_type: 'curp_document', document_label: 'CURP', status: 'verified', verified_by: 'staff-adm-ibime-1', verified_at: '2026-09-21T10:05:00Z', file_name: 'curp_luciana_salgado.pdf', created_at: '2026-09-13T09:02:00Z' },
  { id: 'doc-021-c', lead_id: 'lead-021', candidate_id: 'cand-021', document_type: 'medical_report', document_label: 'Certificado Médico Oficial', status: 'verified', verified_by: 'staff-adm-ibime-1', verified_at: '2026-09-21T10:10:00Z', file_name: 'certificado_medico_luciana.pdf', created_at: '2026-09-13T09:10:00Z' },
  { id: 'doc-021-d', lead_id: 'lead-021', document_type: 'proof_of_address', document_label: 'Comprobante de Domicilio CFE', status: 'verified', verified_by: 'staff-adm-ibime-1', verified_at: '2026-09-21T10:15:00Z', file_name: 'comprobante_cfe_salgado.pdf', created_at: '2026-09-13T09:15:00Z' },
];

// ============================================================
// EVENTOS DE CAPTACIÓN
// ============================================================

export const CRM_EVENTS_SEED: CrmEvent[] = [
  {
    id: 'evt-001',
    school_id: 'sch-ibime',
    campus_id: 'montes',
    name: 'Open House IBIME Montes — Ciclo 2027-2028',
    event_type: 'open_house',
    description: 'Recorrido guiado por todas las instalaciones del campus matriz. Incluye demostración de laboratorio STEAM, clase muestra de inglés Cambridge y show de robótica.',
    event_date: '2026-10-15',
    start_time: '09:00',
    end_time: '13:00',
    location: 'Campus Montes — Auditorio Principal',
    capacity: 60,
    cost_mxn: 15000,
    status: 'planned',
    created_at: '2026-09-20T08:00:00Z',
    attendees_count: 12,
    attended_count: 0,
    enrolled_from_event: 0,
  },
  {
    id: 'evt-002',
    school_id: 'sch-ibime',
    name: 'Feria de Colegios Ecatepec 2026',
    event_type: 'school_fair',
    description: 'Participación con stand institucional en la Feria Anual de Colegios del municipio de Ecatepec.',
    event_date: '2026-09-14',
    start_time: '10:00',
    end_time: '17:00',
    location: 'Centro de Convenciones Ecatepec',
    capacity: 200,
    cost_mxn: 28000,
    status: 'completed',
    created_at: '2026-08-15T10:00:00Z',
    attendees_count: 35,
    attended_count: 28,
    enrolled_from_event: 4,
  },
];

export const CRM_EVENT_ATTENDEES_SEED: CrmEventAttendee[] = [
  { id: 'att-001', event_id: 'evt-002', lead_id: 'lead-006', rsvp_status: 'attended', check_in_at: '2026-09-14T10:15:00Z', feedback_rating: 5, feedback_notes: 'Excelente presentación. Las instalaciones nos gustaron mucho.', created_at: '2026-09-12T08:00:00Z', lead_tutor_name: 'Lic. Javier Pineda', lead_student_name: 'Leonardo Daniel Pineda' },
];
